"""Transit and cosmic calendar regressions.

The reference cases in ``tests/fixtures/astrology_reference_cases.json`` carry
their own provenance: entries marked ``verified_independently`` come from
outside authorities (NASA eclipse catalogue, published equinox and retrograde
times) and are the real regression tests. Entries generated by this engine are
marked as such and only guard against accidental change.
"""

from __future__ import annotations

import json
from datetime import UTC, date, datetime, time, timedelta
from pathlib import Path

import pytest

from app.domain.astrology import BirthData, separation
from app.domain.calendar import CosmicEventType, EclipseSubtype
from app.domain.enums import AspectType, HouseSystem, Planet
from app.domain.transit import PassDirection, TransitStatus, TransitTargetType
from app.services.astrology.calendar import CosmicCalendarEngine
from app.services.astrology.returns import ReturnEngine
from app.services.astrology.skyfield_engine import get_engine
from app.services.astrology.transits import TransitEngine, transit_orb_limit

FIXTURES = json.loads(
    (Path(__file__).parent / "fixtures" / "astrology_reference_cases.json").read_text(
        encoding="utf-8"
    )
)


@pytest.fixture(scope="module")
def chart():
    case = next(item for item in FIXTURES["charts"] if item["id"] == "istanbul_1992")
    data = case["input"]
    birth = BirthData(
        birth_date=date.fromisoformat(data["birth_date"]),
        birth_time=time.fromisoformat(data["birth_time"]),
        timezone=data["timezone"],
        latitude=data["latitude"],
        longitude=data["longitude"],
        house_system=HouseSystem(data["house_system"]),
    )
    return get_engine().natal_chart(birth)


@pytest.fixture(scope="module")
def transits():
    return TransitEngine()


@pytest.fixture(scope="module")
def calendar():
    return CosmicCalendarEngine()


@pytest.fixture(scope="module")
def week_scan(chart, transits):
    start = datetime(2026, 9, 23, tzinfo=UTC)
    return transits.scan(
        chart,
        start=start,
        end=start + timedelta(days=7),
        reference=start + timedelta(hours=12),
        chart_fingerprint="fixture",
    )


# --------------------------------------------------------- reference chart


def test_reference_chart_matches_fixture(chart):
    case = next(item for item in FIXTURES["charts"] if item["id"] == "istanbul_1992")
    expected = case["expected"]

    assert chart.birth_data.utc_datetime.isoformat() == expected["utc_datetime"]
    assert chart.birth_data.utc_offset_hours == expected["utc_offset_hours"]
    assert chart.sun.sign.value == expected["sun"]["sign"]
    assert chart.moon.sign.value == expected["moon"]["sign"]
    assert (
        separation(chart.angles.ascendant, expected["ascendant"]["longitude"])
        < expected["ascendant"]["tolerance_degrees"]
    )
    assert (
        separation(chart.angles.midheaven, expected["midheaven"]["longitude"])
        < expected["midheaven"]["tolerance_degrees"]
    )
    assert chart.house_system.value == expected["house_system_used"]


# --------------------------------------------------------- exact timing


def test_exact_times_are_real_perfections(week_scan, transits):
    """At every reported exact instant the aspect really is exact."""
    checked = 0
    for event in week_scan.events:
        target = event.metadata["target_longitude"]
        for item in event.passes:
            longitude = transits.sampler.value_at(
                event.transiting_body, item.exact_at
            )
            orb = abs(separation(longitude, target) - event.aspect_type.angle)
            assert orb < 0.02, f"{event.id} pass {item.pass_number} orb {orb}"
            checked += 1
    assert checked > 0


def test_passes_are_ordered_and_numbered(week_scan):
    for event in week_scan.events:
        numbers = [item.pass_number for item in event.passes]
        assert numbers == list(range(1, len(numbers) + 1))
        moments = [item.exact_at for item in event.passes]
        assert moments == sorted(moments)


def test_window_contains_every_pass(week_scan):
    for event in week_scan.events:
        for item in event.passes:
            assert event.start_at <= item.exact_at <= event.end_at


def test_orb_at_window_edges_is_the_limit(week_scan, transits):
    """The window is where the orb crosses its limit, not a guess."""
    for event in week_scan.events:
        if event.window_clipped:
            continue
        target = event.metadata["target_longitude"]
        for edge in (event.start_at, event.end_at):
            longitude = transits.sampler.value_at(event.transiting_body, edge)
            orb = abs(separation(longitude, target) - event.aspect_type.angle)
            assert orb == pytest.approx(event.maximum_orb, abs=0.1)


def test_applying_and_separating_follow_the_exact_time(week_scan):
    for event in week_scan.events:
        if event.exact_at is None:
            continue
        if event.applying:
            assert event.exact_at >= week_scan.reference
        else:
            assert event.exact_at <= week_scan.reference


def test_status_matches_the_reference_instant(week_scan):
    for event in week_scan.events:
        if event.start_at > week_scan.reference:
            assert event.status is TransitStatus.APPROACHING
        elif event.exact_at and abs(
            (week_scan.reference - event.exact_at).total_seconds()
        ) <= 12 * 3600:
            assert event.status is TransitStatus.EXACT


def test_strength_is_bounded_and_deterministic(chart, transits, week_scan):
    for event in week_scan.events:
        assert 0 <= event.strength <= 100

    start = datetime(2026, 9, 23, tzinfo=UTC)
    again = TransitEngine().scan(
        chart,
        start=start,
        end=start + timedelta(days=7),
        reference=start + timedelta(hours=12),
        chart_fingerprint="fixture",
    )
    assert [event.id for event in again.events] == [
        event.id for event in week_scan.events
    ]
    assert [event.strength for event in again.events] == [
        event.strength for event in week_scan.events
    ]


def test_orbs_never_exceed_the_policy(week_scan):
    for event in week_scan.events:
        assert event.maximum_orb == pytest.approx(
            transit_orb_limit(event.transiting_body, event.aspect_type), abs=1e-9
        )


# ------------------------------------------------------ retrograde passes


def test_retrograde_transit_perfects_more_than_once(chart, transits):
    """A slow planet that stations inside its orb perfects several times.

    Over a year at least one outer-planet transit must show multiple passes
    with a retrograde one among them - that is the whole reason ``passes``
    exists.
    """
    start = datetime(2026, 1, 1, tzinfo=UTC)
    scan = transits.scan(
        chart,
        start=start,
        end=start + timedelta(days=365),
        reference=start,
        include_moon=False,
        chart_fingerprint="multi",
    )

    multi = [event for event in scan.events if event.is_multi_pass]
    assert multi, "no multi-pass transit found in a whole year"

    retrograde_passes = [
        item
        for event in multi
        for item in event.passes
        if item.direction is PassDirection.RETROGRADE
    ]
    assert retrograde_passes

    for event in multi:
        # A three-pass transit goes direct, retrograde, direct.
        directions = [item.direction for item in event.passes]
        assert PassDirection.RETROGRADE in directions or len(directions) == 2
        assert event.strength >= 0


def test_pass_direction_matches_the_speed_sign(week_scan):
    for event in week_scan.events:
        for item in event.passes:
            if item.direction is PassDirection.RETROGRADE:
                assert item.speed < 0
            else:
                assert item.speed >= 0


# ----------------------------------------------------------- house ingress


def test_house_ingress_is_a_real_cusp_crossing(chart, transits, week_scan):
    assert week_scan.ingresses
    cusps = {house.number: house.cusp_longitude for house in chart.houses}

    for ingress in week_scan.ingresses:
        longitude = transits.sampler.value_at(ingress.planet, ingress.entered_at)
        cusp = cusps[ingress.to_house if not ingress.retrograde else ingress.from_house]
        assert separation(longitude, cusp) < 0.05
        assert 1 <= ingress.from_house <= 12
        assert 1 <= ingress.to_house <= 12
        assert ingress.from_house != ingress.to_house


def test_retrograde_re_entry_is_marked(chart, transits):
    """A retrograding planet leaves a house and comes back; the second entry
    is flagged rather than reported as a fresh ingress."""
    start = datetime(2026, 1, 1, tzinfo=UTC)
    scan = transits.scan(
        chart,
        start=start,
        end=start + timedelta(days=365),
        reference=start,
        include_moon=False,
        chart_fingerprint="ingress",
    )
    assert scan.ingresses
    re_entries = [item for item in scan.ingresses if item.re_entry]
    assert re_entries, "expected at least one house re-entry in a year"
    assert any(item.retrograde for item in scan.ingresses)


def test_ingress_exit_follows_entry(week_scan):
    for ingress in week_scan.ingresses:
        if ingress.estimated_exit_at is not None:
            assert ingress.estimated_exit_at > ingress.entered_at


# ------------------------------------------------------------- calendar


def test_moon_phases_are_quarter_turns(calendar):
    start = datetime(2026, 4, 1, tzinfo=UTC)
    events = calendar.events(
        start,
        start + timedelta(days=40),
        include_stations=False,
        include_ingresses=False,
        include_aspects=False,
        include_eclipses=False,
    )
    phases = [event for event in events if event.type.is_moon_phase]
    assert len(phases) >= 4

    expected = {
        CosmicEventType.NEW_MOON: 0.0,
        CosmicEventType.FIRST_QUARTER: 90.0,
        CosmicEventType.FULL_MOON: 180.0,
        CosmicEventType.LAST_QUARTER: 270.0,
    }
    for event in phases:
        sun = calendar.sampler.value_at(Planet.SUN, event.exact_at)
        moon = calendar.sampler.value_at(Planet.MOON, event.exact_at)
        elongation = (moon - sun) % 360.0
        assert separation(elongation, expected[event.type]) < 0.05


def test_published_eclipses_are_found_and_nothing_is_invented(calendar):
    """All four 2026 eclipses, on the published dates, and no false positives."""
    start = datetime(2026, 1, 1, tzinfo=UTC)
    end = datetime(2026, 12, 31, 23, 59, tzinfo=UTC)
    events = calendar.events(
        start,
        end,
        include_stations=False,
        include_ingresses=False,
        include_aspects=False,
    )
    eclipses = [event for event in events if event.type.is_eclipse]
    expected = FIXTURES["eclipses_2026"]

    assert len(eclipses) == len(expected), (
        "eclipse count differs from the NASA catalogue: "
        f"{[event.exact_at.date().isoformat() for event in eclipses]}"
    )

    for case in expected:
        match = next(
            (
                event
                for event in eclipses
                if event.exact_at.date().isoformat() == case["date"]
            ),
            None,
        )
        assert match is not None, f"missing eclipse {case['id']}"
        assert match.type.value == case["type"]

        if case["type"] == "lunar_eclipse":
            assert match.eclipse_subtype is not None
            assert match.eclipse_subtype.value == case["engine_subtype_expected"]
        else:
            # Solar subtype needs Besselian elements: null, never guessed.
            assert match.eclipse_subtype is None


def test_eclipses_sit_close_to_a_node(calendar):
    start = datetime(2026, 1, 1, tzinfo=UTC)
    events = calendar.events(
        start,
        start + timedelta(days=365),
        include_stations=False,
        include_ingresses=False,
        include_aspects=False,
    )
    for event in events:
        if event.type.is_eclipse:
            assert event.node_distance is not None
            assert event.node_distance < 19.0


def test_published_retrograde_windows(calendar):
    start = datetime(2026, 1, 1, tzinfo=UTC)
    end = datetime(2026, 12, 31, 23, 59, tzinfo=UTC)
    periods = calendar.retrograde_periods(start, end)

    for case in FIXTURES["retrograde_periods_2026"]:
        planet = Planet(case["planet"])
        expected_start = date.fromisoformat(case["station_retrograde"])
        match = next(
            (
                period
                for period in periods
                if period.planet is planet
                and abs((period.start_at.date() - expected_start).days)
                <= case["tolerance_days"]
            ),
            None,
        )
        assert match is not None, f"missing retrograde window {case['id']}"
        assert (
            abs(
                (
                    match.end_at.date() - date.fromisoformat(case["station_direct"])
                ).days
            )
            <= case["tolerance_days"]
        )


def test_stations_are_where_speed_changes_sign(calendar):
    start = datetime(2026, 1, 1, tzinfo=UTC)
    events = calendar.stations(start, start + timedelta(days=200))
    assert events

    for event in events:
        before = calendar.sampler.speeds_at(
            event.planet, [event.exact_at - timedelta(days=2)]
        )[0]
        after = calendar.sampler.speeds_at(
            event.planet, [event.exact_at + timedelta(days=2)]
        )[0]
        assert before * after < 0
        if event.type is CosmicEventType.STATION_RETROGRADE:
            assert after < 0
        else:
            assert after > 0


def test_ingress_events_land_on_sign_boundaries(calendar):
    start = datetime(2026, 1, 1, tzinfo=UTC)
    events = calendar.ingresses(start, start + timedelta(days=120))
    assert events
    for event in events:
        assert event.longitude is not None
        assert min(event.longitude % 30, 30 - (event.longitude % 30)) < 0.05


def test_mundane_aspects_are_exact(calendar):
    start = datetime(2026, 1, 1, tzinfo=UTC)
    events = calendar.mundane_aspects(start, start + timedelta(days=365))
    for event in events:
        first = calendar.sampler.value_at(event.planet, event.exact_at)
        second = calendar.sampler.value_at(event.secondary_planet, event.exact_at)
        assert separation(first, second) == pytest.approx(
            event.aspect.angle, abs=0.1
        )


# -------------------------------------------------------------- returns


def test_solar_return_puts_the_sun_on_its_natal_degree(chart):
    case = FIXTURES["solar_returns"][0]
    engine = ReturnEngine()
    moment = engine.solar_return_moment(chart, case["year"])
    assert moment is not None

    # Self-verifying: whatever the instant, the Sun must be there.
    from app.services.astrology.sampling import EphemerisSampler

    longitude = EphemerisSampler().value_at(Planet.SUN, moment)
    assert separation(longitude, chart.sun.longitude) < 0.01

    expected = datetime.fromisoformat(case["expected_exact_at"])
    assert abs((moment - expected).total_seconds()) <= case["tolerance_minutes"] * 60


def test_solar_return_chart_is_cast_for_the_return(chart):
    engine = ReturnEngine()
    return_chart = engine.solar_return_chart(chart, 2026)
    assert return_chart is not None
    assert return_chart.kind.value == "solar_return"
    assert return_chart.birth_data is None
    assert len(return_chart.houses) == 12
    assert return_chart.subject.moment_utc.year == 2026


def test_lunar_return_repeats_monthly(chart):
    engine = ReturnEngine()
    first = engine.lunar_return_moment(chart, after=datetime(2026, 1, 1, tzinfo=UTC))
    assert first is not None
    second = engine.lunar_return_moment(chart, after=first + timedelta(days=1))
    assert second is not None
    gap = (second - first).total_seconds() / 86400
    assert 26.0 < gap < 29.0  # sidereal month is 27.32 days
