"""Payments, entitlements, accounting and settlement.

Eleven tables: the store product catalogue, verified store purchases, the
entitlements derived from them, provider events (for once-only processing),
order line items and payment groups, external payment intents, immutable
payment transactions, the ledger, expert payouts and refund requests.

The existing `subscriptions` table is kept and reused as the per-user tier
projection that `User.tier` reads. It is written only from verified
entitlements; see app/services/payments/entitlements.py.

On Postgres, three triggers make the accounting tables mean what they say:

* `payment_transactions` and `ledger_entries` refuse UPDATEs that change any
  money column, and refuse DELETE outright. A refund is a new row, never an
  edit. (Foreign keys may still be nulled - deleting a user must not be
  blocked by the ledger - which is why the check is per column.)
* A DEFERRABLE INITIALLY DEFERRED constraint trigger refuses to commit a
  journal whose debits and credits differ in any currency.

Maintenance that genuinely needs to delete (test scripts cleaning up their own
rows) sets `astro.ledger_maintenance = 'on'` for its transaction. Nothing in
the application does.

Revision ID: 0011_payments_entitlements
Revises: 0010_livekit_calls
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0011_payments_entitlements'
down_revision: Union[str, None] = '0010_livekit_calls'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_provider_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('external_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('transaction_ref', sa.String(length=128), nullable=True),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=12), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_event_id', name='uq_payment_provider_events_event')
    )
    op.create_index('ix_payment_provider_events_received', 'payment_provider_events', ['received_at'], unique=False)
    op.create_table('store_products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('entitlement_code', sa.String(length=80), nullable=False),
    sa.Column('units_per_purchase', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('service_code', sa.String(length=60), nullable=True),
    sa.Column('apple_product_id', sa.String(length=200), nullable=True),
    sa.Column('google_product_id', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("product_type IN ('consumable', 'non_consumable', 'subscription')", name='ck_store_products_type'),
    sa.CheckConstraint('units_per_purchase >= 1', name='ck_store_products_units'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_product_id', name='uq_store_products_apple'),
    sa.UniqueConstraint('code', name='uq_store_products_code'),
    sa.UniqueConstraint('google_product_id', name='uq_store_products_google')
    )
    op.create_table('store_purchases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=10), nullable=False),
    sa.Column('store_product_id', sa.Uuid(), nullable=False),
    sa.Column('store_product_ref', sa.String(length=200), nullable=False),
    sa.Column('purchase_key', sa.String(length=128), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('original_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('purchase_token_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('environment', sa.String(length=12), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renewing', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=40), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('store_consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("environment IN ('production', 'sandbox')", name='ck_store_purchases_environment'),
    sa.CheckConstraint("provider IN ('apple', 'google')", name='ck_store_purchases_provider'),
    sa.CheckConstraint('quantity >= 1', name='ck_store_purchases_quantity'),
    sa.ForeignKeyConstraint(['store_product_id'], ['store_products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'purchase_key', name='uq_store_purchases_key')
    )
    op.create_index('ix_store_purchases_original', 'store_purchases', ['provider', 'original_transaction_id'], unique=False)
    op.create_index('ix_store_purchases_user', 'store_purchases', ['user_id', 'status'], unique=False)
    op.create_table('expert_payouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expert_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('external_reference', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name='ck_expert_payouts_amount'),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expert_payouts_expert', 'expert_payouts', ['expert_id', 'status'], unique=False)
    op.create_table('user_entitlements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entitlement_code', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('store_purchase_id', sa.Uuid(), nullable=True),
    sa.Column('unit_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('environment', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renewing', sa.Boolean(), nullable=True),
    sa.Column('original_transaction_ref', sa.String(length=128), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('subscription', 'credit', 'permanent')", name='ck_user_entitlements_kind'),
    sa.ForeignKeyConstraint(['store_purchase_id'], ['store_purchases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_purchase_id', 'unit_index', name='uq_user_entitlements_unit')
    )
    op.create_index('ix_user_entitlements_lookup', 'user_entitlements', ['user_id', 'entitlement_code', 'status'], unique=False)
    op.create_index('uq_user_entitlements_consumption', 'user_entitlements', ['user_id', 'consumed_ref'], unique=True, postgresql_where=sa.text('consumed_ref IS NOT NULL'), sqlite_where=sa.text('consumed_ref IS NOT NULL'))
    op.create_table('order_line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('unit_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('total_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_classification', sa.String(length=30), nullable=False),
    sa.Column('provider_rail', sa.String(length=30), nullable=False),
    sa.Column('line_status', sa.String(length=20), nullable=False),
    sa.Column('store_product_code', sa.String(length=80), nullable=True),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('commission_basis_points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('platform_fee_minor', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('expert_net_minor', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('tax_source', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('platform_fee_minor >= 0 AND expert_net_minor >= 0', name='ck_order_line_items_split'),
    sa.CheckConstraint('quantity >= 1', name='ck_order_line_items_quantity'),
    sa.CheckConstraint('tax_amount_minor IS NULL OR tax_amount_minor >= 0', name='ck_order_line_items_tax'),
    sa.CheckConstraint('total_minor IS NULL OR total_minor >= 0', name='ck_order_line_items_total'),
    sa.CheckConstraint('unit_amount_minor IS NULL OR unit_amount_minor >= 0', name='ck_order_line_items_unit'),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_line_items_order', 'order_line_items', ['order_id'], unique=False)
    op.create_table('order_payment_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('rail', sa.String(length=30), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('satisfied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_intent_id', sa.Uuid(), nullable=True),
    sa.Column('store_purchase_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor IS NULL OR amount_minor >= 0', name='ck_order_payment_groups_amount'),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_purchase_id'], ['store_purchases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'classification', name='uq_order_payment_groups_class')
    )
    op.create_table('payment_intents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('payment_group_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('rail', sa.String(length=30), nullable=False),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('external_reference', sa.String(length=128), nullable=True),
    sa.Column('refunded_minor', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name='ck_payment_intents_amount'),
    sa.CheckConstraint('refunded_minor >= 0 AND refunded_minor <= amount_minor', name='ck_payment_intents_refunded'),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_group_id'], ['order_payment_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_reference', name='uq_payment_intents_external'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_payment_intents_idem')
    )
    op.create_index('ix_payment_intents_order', 'payment_intents', ['order_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('rail', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('payment_intent_id', sa.Uuid(), nullable=True),
    sa.Column('store_purchase_id', sa.Uuid(), nullable=True),
    sa.Column('related_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('external_transaction_ref', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('provider_fee_minor', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_safe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.CheckConstraint('amount_minor IS NULL OR amount_minor >= 0', name='ck_payment_transactions_amount'),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['payment_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_purchase_id'], ['store_purchases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_transaction_ref', 'type', name='uq_payment_transactions_external')
    )
    op.create_index('ix_payment_transactions_intent', 'payment_transactions', ['payment_intent_id'], unique=False)
    op.create_index('ix_payment_transactions_order', 'payment_transactions', ['order_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journal_key', sa.String(length=120), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('payment_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('account_type', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("direction IN ('debit', 'credit')", name='ck_ledger_entries_direction'),
    sa.CheckConstraint('amount_minor > 0', name='ck_ledger_entries_amount'),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_key', 'line_no', name='uq_ledger_entries_line')
    )
    op.create_index('ix_ledger_entries_account', 'ledger_entries', ['account_type', 'account_id', 'currency'], unique=False)
    op.create_index('ix_ledger_entries_order', 'ledger_entries', ['order_id'], unique=False)
    op.create_table('refund_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('payment_intent_id', sa.Uuid(), nullable=True),
    sa.Column('store_purchase_id', sa.Uuid(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('decision_basis', sa.String(length=80), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('refund_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=40), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name='ck_refund_requests_amount'),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['refund_transaction_id'], ['payment_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_purchase_id'], ['store_purchases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_refund_requests_idem')
    )
    op.create_index('ix_refund_requests_order', 'refund_requests', ['order_id'], unique=False)
    op.create_index('ix_refund_requests_status', 'refund_requests', ['status'], unique=False)
    # ### end Alembic commands ###

    # --- accounting guarantees (Postgres only) -----------------------------
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(
            """
            CREATE OR REPLACE FUNCTION astro_forbid_money_rewrite() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    IF coalesce(current_setting('astro.ledger_maintenance', true), '') = 'on' THEN
                        RETURN OLD;
                    END IF;
                    RAISE EXCEPTION '% rows are append-only', TG_TABLE_NAME
                        USING ERRCODE = 'integrity_constraint_violation';
                END IF;
                IF TG_TABLE_NAME = 'ledger_entries' THEN
                    IF NEW.journal_key IS DISTINCT FROM OLD.journal_key
                       OR NEW.line_no IS DISTINCT FROM OLD.line_no
                       OR NEW.account_type IS DISTINCT FROM OLD.account_type
                       OR NEW.account_id IS DISTINCT FROM OLD.account_id
                       OR NEW.direction IS DISTINCT FROM OLD.direction
                       OR NEW.amount_minor IS DISTINCT FROM OLD.amount_minor
                       OR NEW.currency IS DISTINCT FROM OLD.currency THEN
                        RAISE EXCEPTION 'ledger entries are immutable'
                            USING ERRCODE = 'integrity_constraint_violation';
                    END IF;
                ELSE
                    IF NEW.type IS DISTINCT FROM OLD.type
                       OR NEW.amount_minor IS DISTINCT FROM OLD.amount_minor
                       OR NEW.currency IS DISTINCT FROM OLD.currency
                       OR NEW.external_transaction_ref IS DISTINCT FROM OLD.external_transaction_ref
                       OR NEW.provider IS DISTINCT FROM OLD.provider THEN
                        RAISE EXCEPTION 'payment transactions are immutable'
                            USING ERRCODE = 'integrity_constraint_violation';
                    END IF;
                END IF;
                RETURN NEW;
            END $$;
            """
        )
        for table in ("ledger_entries", "payment_transactions"):
            op.execute(
                f"CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE OR DELETE "
                f"ON {table} FOR EACH ROW EXECUTE FUNCTION astro_forbid_money_rewrite()"
            )

        op.execute(
            """
            CREATE OR REPLACE FUNCTION astro_check_journal_balance() RETURNS trigger
            LANGUAGE plpgsql AS $$
            DECLARE
                imbalance record;
            BEGIN
                SELECT currency,
                       sum(CASE WHEN direction = 'debit' THEN amount_minor ELSE 0 END) AS debits,
                       sum(CASE WHEN direction = 'credit' THEN amount_minor ELSE 0 END) AS credits
                  INTO imbalance
                  FROM ledger_entries
                 WHERE journal_key = NEW.journal_key
              GROUP BY currency
                HAVING sum(CASE WHEN direction = 'debit' THEN amount_minor ELSE 0 END)
                    <> sum(CASE WHEN direction = 'credit' THEN amount_minor ELSE 0 END)
                 LIMIT 1;
                IF FOUND THEN
                    RAISE EXCEPTION 'journal % does not balance in %', NEW.journal_key, imbalance.currency
                        USING ERRCODE = 'integrity_constraint_violation';
                END IF;
                RETURN NULL;
            END $$;
            """
        )
        op.execute(
            "CREATE CONSTRAINT TRIGGER trg_ledger_entries_balanced AFTER INSERT "
            "ON ledger_entries DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
            "EXECUTE FUNCTION astro_check_journal_balance()"
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS trg_ledger_entries_balanced ON ledger_entries")
        op.execute("DROP TRIGGER IF EXISTS trg_ledger_entries_immutable ON ledger_entries")
        op.execute(
            "DROP TRIGGER IF EXISTS trg_payment_transactions_immutable ON payment_transactions"
        )
        op.execute("DROP FUNCTION IF EXISTS astro_check_journal_balance()")
        op.execute("DROP FUNCTION IF EXISTS astro_forbid_money_rewrite()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refund_requests_status', table_name='refund_requests')
    op.drop_index('ix_refund_requests_order', table_name='refund_requests')
    op.drop_table('refund_requests')
    op.drop_index('ix_ledger_entries_order', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_account', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_payment_transactions_order', table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_intent', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index('ix_payment_intents_order', table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_table('order_payment_groups')
    op.drop_index('ix_order_line_items_order', table_name='order_line_items')
    op.drop_table('order_line_items')
    op.drop_index('uq_user_entitlements_consumption', table_name='user_entitlements', postgresql_where=sa.text('consumed_ref IS NOT NULL'), sqlite_where=sa.text('consumed_ref IS NOT NULL'))
    op.drop_index('ix_user_entitlements_lookup', table_name='user_entitlements')
    op.drop_table('user_entitlements')
    op.drop_index('ix_expert_payouts_expert', table_name='expert_payouts')
    op.drop_table('expert_payouts')
    op.drop_index('ix_store_purchases_user', table_name='store_purchases')
    op.drop_index('ix_store_purchases_original', table_name='store_purchases')
    op.drop_table('store_purchases')
    op.drop_table('store_products')
    op.drop_index('ix_payment_provider_events_received', table_name='payment_provider_events')
    op.drop_table('payment_provider_events')
    # ### end Alembic commands ###
