import 'package:flutter/widgets.dart';

/// B12 keys keep TR/EN paired. AZ intentionally falls back to TR until reviewed.
String b12(BuildContext context, String key) {
  final value = _copy[key];
  if (value == null) return key.replaceAll('_', ' ');
  return Localizations.localeOf(context).languageCode == 'en'
      ? value.$2
      : value.$1;
}

/// The same copy by language code, for code that has no BuildContext (a
/// root-level snackbar, for instance).
String b12In(String languageCode, String key) {
  final value = _copy[key];
  if (value == null) return key.replaceAll('_', ' ');
  return languageCode == 'en' ? value.$2 : value.$1;
}

const _copy = <String, (String, String)>{
  'register_step_account': (
    '1 / 2 · Hesap bilgileri',
    '1 / 2 · Account details',
  ),
  'register_step_birth': ('2 / 2 · Doğum bilgileri', '2 / 2 · Birth details'),
  'register_next': ('Devam et', 'Continue'),
  'account_deletion_help': (
    'Hesap silme bilgisi',
    'Account deletion information',
  ),
  'subscription_support': ('Destek', 'Support'),
  'subscription_manage': (
    'Aboneliği yönet / iptal et',
    'Manage / cancel subscription',
  ),
  'subscription_choose_store': (
    'Aboneliği satın aldığın mağazayı seç. Ödeme dönemi ve iptal işlemleri mağazada yönetilir.',
    'Choose the store where you subscribed. Billing periods and cancellation are managed there.',
  ),
  'subscription_link_failed': (
    'Bağlantı açılamadı. İnternet bağlantını kontrol edip tekrar dene.',
    'Could not open the link. Check your connection and try again.',
  ),
  'subscription_terms': ('Kullanım koşulları', 'Terms of use'),
  'subscription_privacy': ('Gizlilik politikası', 'Privacy policy'),
  'subscription_renewal': (
    'Abonelik seçtiğin aylık veya yıllık dönem sonunda otomatik yenilenir. İptal ve dönem değişikliği, satın aldığın mağazanın Abonelikler bölümünden yapılır. Uzman görüşmeleri ayrı ücretlendirilir.',
    'Subscriptions renew automatically at the end of the selected monthly or yearly period. Cancel or change the period in the purchasing store’s Subscriptions section. Expert sessions are charged separately.',
  ),
  'subscription_period_change': (
    'Ödeme dönemini değiştir',
    'Change billing period',
  ),
  'subscription_period_note': (
    'Mevcut ödeme dönemini, yenileme tarihini ve değişiklik ücretini mağazada görebilirsin.',
    'View your current billing period, renewal date and any change in price in the store.',
  ),
  'subscription_switch_note': (
    'Plan değişikliğinin ücreti ve başlayacağı tarih, onaydan önce mağazada gösterilir.',
    'The store shows the charge and effective date of a plan change before confirmation.',
  ),
  'subscription_benefit_note': (
    'Günlük rehberliğin için Premium; ilişki ve uzun dönem analizleri için Kozmik+. Ücretsiz kullanmaya devam edebilirsin.',
    'Choose Premium for daily guidance, or Cosmic+ for relationships and long-term insights. You can keep using the free plan.',
  ),
  'subscription_focus': (
    'Açmak istediğin özellik için önerilen plan: {plan}',
    'Recommended plan for this feature: {plan}',
  ),
  'store_reload': ('Fiyatları yeniden yükle', 'Reload prices'),
  'store_loading': ('Fiyatlar yükleniyor…', 'Loading prices…'),
  'store_retry_note': (
    'Mağaza fiyatlarına ulaşılamadı. Bağlantını kontrol edip yeniden dene.',
    'Store prices could not be loaded. Check your connection and try again.',
  ),
  'required_plan_feature': (
    'Bu özellik {plan} planına dahil.',
    'This feature is included in {plan}.',
  ),
  'unlock_with_plan': ('{plan} ile aç', 'Unlock with {plan}'),
  'explore_search_hint': (
    'Özellik ara: ilişki, tarot, doğum haritası…',
    'Find a feature: relationships, tarot, birth chart…',
  ),
  'explore_category_all': ('Tümü', 'All'),
  'explore_category_astrology': ('Astroloji', 'Astrology'),
  'explore_category_relationships': ('İlişkiler', 'Relationships'),
  'explore_category_spreads': ('Açılımlar', 'Readings'),
  'explore_category_consultants': ('Danışmanlar', 'Consultants'),
  'explore_no_results': (
    'Eşleşen özellik bulunamadı. Başka bir kelime dene.',
    'No matching features. Try another word.',
  ),
  'home_draw_action': ('Kartını çek', 'Draw a card'),
  'home_forecast_action': ('Günlük yorum', 'Daily reading'),
  'home_expert_action': ('Danışman bul', 'Find an expert'),
  'home_score_help': ('Bu puan ne anlatıyor?', 'What does this score mean?'),
  'home_score_explanation': (
    'Puan, seçilen günün astrolojik yorumunu özetler; bir olasılık veya kesin sonuç ölçümü değildir. Ayrıntılarda seni etkileyen göstergeleri inceleyebilirsin.',
    'The score summarizes the astrological reading for the selected day; it is not a probability or a measurement of certain outcomes. Explore the influences in the details.',
  ),
  'reason_intent_short': ('Niyet', 'Intent'),
  'reason_element_short': ('Element', 'Element'),
  'reason_placement_short': ('Harita', 'Chart'),
  'reason_planet_short': ('Gezegen', 'Planet'),
  'reason_moon_short': ('Ay', 'Moon'),
  'reason_transit_short': ('Transit', 'Transit'),
  'reason_other_short': ('Bağ', 'Link'),
  'relationship_analysis': ('İlişki Analizi', 'Relationship Analysis'),
  'explore_relationships': ('İlişkiler', 'Relationships'),
  'explore_forecasts': ('Öngörüler', 'Forecasts'),
  'explore_returns': ('Dönüş Haritaları', 'Return Charts'),
  'explore_natal_sub': (
    'Gezegenlerin, evlerin ve açıların',
    'Your planets, houses and aspects',
  ),
  'explore_transits_sub': (
    'Bugün ve yakında seni etkileyenler',
    'What affects you now and soon',
  ),
  'explore_relationship_sub': (
    'Sinastri, Composite ve Davison tek yerde',
    'Synastry, composite and Davison in one place',
  ),
  'explore_synastry_sub': (
    'İlişki uyumunuz ve birbirinize etkileriniz',
    'Cross-chart aspects and house overlays',
  ),
  'explore_composite_sub': (
    'İlişkinizin ortak dinamiği',
    'The chart of the relationship',
  ),
  'explore_davison_sub': (
    'İlişkinizin zaman içindeki temaları',
    'Midpoint in time and space',
  ),
  'explore_daily_sub': (
    'Bugünün kişisel öngörüsü',
    "Today's personal forecast",
  ),
  'explore_monthly_sub': (
    'Ayın temaları ve önemli tarihleri',
    "The month's themes and key dates",
  ),
  'explore_yearly_sub': (
    'Yılın büyük transitleri',
    "The year's major transits",
  ),
  'explore_solar_sub': (
    'Doğum günü yılının haritası',
    'The chart of your birthday year',
  ),
  'explore_lunar_sub': ('Aylık Ay dönüşü', 'Your monthly Moon return'),
  'explore_moon_sub': (
    'Ay fazı ve bugün ne için uygun',
    'Moon phase and what today suits',
  ),
  'explore_stone_sub': (
    'Haritana ve niyetine göre taş',
    'A stone for your chart and intent',
  ),
  'explore_numerology_sub': (
    'Yaşam yolu ve kişisel sayıların',
    'Life path and personal numbers',
  ),
  'explore_calendar_sub': (
    'Ay fazları, retrolar, tutulmalar',
    'Moon phases, retrogrades, eclipses',
  ),
  'explore_horary_sub': (
    'Tek bir soruya haritayla bak',
    'Look at one question with a chart',
  ),
  'cards_unit': ('kart', 'cards'),
  'stone_alternatives': ('Diğer uygun taşlar', 'Other good matches'),
  'reason_intent': ('Niyetinle uyumlu', 'Fits your intent'),
  'reason_element': ('Element dengesi', 'Element balance'),
  'reason_placement': ('Haritanla bağlantılı', 'Linked to your chart'),
  'reason_planet': ('Gezegen bağlantısı', 'Planet link'),
  'reason_moon': ('Bugünkü Ay', "Today's Moon"),
  'reason_transit': ('Bugünkü transit', "Today's transit"),
  'reason_other': ('Astrolojik bağ', 'Astrological link'),
  'exact_phase_moment': ('Tam %s anı', 'Exact %s'),
  'affected_houses': ('Etkilenen evler', 'Affected houses'),
  'natal_prefix': ('natal', 'natal'),
  'north_node_short': ('K. Ay Düğümü', 'N. Node'),
  'south_node_short': ('G. Ay Düğümü', 'S. Node'),
  'houses_title': ('Evler', 'Houses'),
  'retro_short': ('Retro', 'Retro'),
  'retrograde': ('Retro hareket', 'Retrograde'),
  'nature_supportive': ('Destekleyici', 'Supportive'),
  'nature_challenging': ('Zorlayıcı', 'Challenging'),
  'nature_prominent': ('Belirgin', 'Prominent'),
  'influences_title': (
    'Bu yorumu oluşturan etkiler',
    'What shaped this answer',
  ),
  'explore_astrology': ('Astroloji', 'Astrology'),
  'explore_spreads': ('Açılımlar', 'Readings'),
  'explore_personal': ('Kişisel Rehber', 'Personal Guide'),
  'explore_experts': ('Uzman', 'Experts'),
  'forecast_daily': ('Günlük Öngörü', 'Daily Forecast'),
  'forecast_weekly': ('Haftalık Öngörü', 'Weekly Forecast'),
  'forecast_monthly': ('Aylık Öngörü', 'Monthly Forecast'),
  'forecast_yearly': ('Yıllık Öngörü', 'Yearly Forecast'),
  'solar_return': ('Solar Return', 'Solar Return'),
  'lunar_return': ('Lunar Return', 'Lunar Return'),
  'astro_ai': ('Astro AI', 'Astro AI'),
  'stone_guide': ('Taş Rehberi', 'Stone Guide'),
  'numerology': ('Numeroloji', 'Numerology'),
  'moon_guide': ('Ay Rehberi', 'Moon Guide'),
  'experts_astrologers': ('Astrologlar', 'Astrologers'),
  'experts_tarot': ('Tarot Danışmanları', 'Tarot Readers'),
  'experts_rune': ('Rün Danışmanları', 'Rune Readers'),
  'expert_chat': ('Yazışarak Danış', 'Chat'),
  'expert_voice': ('Sesli Görüşme', 'Voice Call'),
  'expert_video': ('Görüntülü Görüşme', 'Video Call'),
  'expert_written': ('Yazılı Analiz', 'Written Analysis'),
  'illumination': ('Aydınlanma', 'Illumination'),
  'moon_natal_house': ('Ay\'ın geçtiği ev', 'House the Moon crosses'),
  'house': ('ev', 'house'),
  'next_phase': ('Sonraki faz', 'Next phase'),
  'moon_enters': ('Ay giriyor:', 'Moon enters'),
  'good_for_today': ('Bugün ne için uygun?', 'What today suits'),
  'careful_today': ('Bugün neye dikkat edilmeli?', 'What to watch today'),
  'nothing_notable': ('Belirgin bir etki yok.', 'Nothing notable.'),
  'moon_aspects_sky': (
    'Ay\'ın gökyüzündeki açıları',
    'Moon\'s aspects in the sky',
  ),
  'moon_aspects_natal': (
    'Ay\'ın haritana açıları',
    'Moon\'s aspects to your chart',
  ),
  'today': ('Bugün', 'Today'),
  'tomorrow': ('Yarın', 'Tomorrow'),
  'this_week': ('Bu Hafta', 'This Week'),
  'this_month': ('Bu Ay', 'This Month'),
  'pick_date': ('Tarih Seç', 'Pick a date'),
  'no_transits': (
    'Bu aralıkta öne çıkan transit yok.',
    'No notable transits in this window.',
  ),
  'transits_active': ('Etkide olanlar', 'Active now'),
  'transits_approaching': ('Yaklaşanlar', 'Approaching'),
  'transits_upcoming': ('İleride', 'Upcoming'),
  'status_approaching': ('Yaklaşıyor', 'Approaching'),
  'status_active': ('Etkide', 'Active'),
  'status_separating': ('Ayrılıyor', 'Separating'),
  'start': ('Başlangıç', 'Start'),
  'peak': ('Zirve', 'Peak'),
  'end': ('Bitiş', 'End'),
  'applying': ('güçleniyor', 'applying'),
  'separating_short': ('zayıflıyor', 'separating'),
  'planet': ('Gezegen', 'Planet'),
  'sign': ('Burç', 'Sign'),
  'degree': ('Derece', 'Degree'),
  'numerology_intro': (
    'Sayılar doğum tarihinden ve doğum adından Pisagor sistemiyle hesaplanır.',
    'Numbers are calculated from your birth date and birth name with the Pythagorean system.',
  ),
  'full_birth_name': (
    'Tam doğum adı (isteğe bağlı)',
    'Full birth name (optional)',
  ),
  'full_birth_name_hint': (
    'Boş bırakırsan profil adın kullanılır',
    'Leave empty to use your profile name',
  ),
  'num_life_path': ('Yaşam Yolu', 'Life Path'),
  'num_destiny': ('Kader Sayısı', 'Destiny'),
  'num_soul_urge': ('Ruh Arzusu', 'Soul Urge'),
  'num_personality': ('Kişilik Sayısı', 'Personality'),
  'num_birthday': ('Doğum Günü Sayısı', 'Birthday Number'),
  'num_personal_year': ('Kişisel Yıl', 'Personal Year'),
  'num_personal_month': ('Kişisel Ay', 'Personal Month'),
  'numerology_method': (
    'Pisagor sistemi · 11, 22 ve 33 usta sayı olarak korunur · Y ünsüz sayılır.',
    'Pythagorean system · 11, 22 and 33 are kept as master numbers · Y counts as a consonant.',
  ),
  'master_number': ('Usta sayı', 'Master number'),
  'stone_today': ('Bugünün Taşı', 'Stone of the Day'),
  'stone_personal': ('Sana Özel', 'Personal Stone'),
  'stone_intent': ('Niyetin', 'Your intent'),
  'intent_any': ('Tümü', 'Any'),
  'intent_love': ('Aşk', 'Love'),
  'intent_money': ('Para', 'Money'),
  'intent_career': ('Kariyer', 'Career'),
  'intent_calm': ('Sakinlik', 'Calm'),
  'intent_motivation': ('Motivasyon', 'Motivation'),
  'intent_communication': ('İletişim', 'Communication'),
  'intent_protection': ('Korunma', 'Protection'),
  'intent_confidence': ('Özgüven', 'Confidence'),
  'intent_meditation': ('Meditasyon', 'Meditation'),
  'element_balance': ('Element dengen', 'Your element balance'),
  'element_fire': ('Ateş', 'Fire'),
  'element_earth': ('Toprak', 'Earth'),
  'element_air': ('Hava', 'Air'),
  'element_water': ('Su', 'Water'),
  'stone_best_match': ('En uygun taş', 'Best match'),
  'why_suggested': ('Neden önerildi?', 'Why this stone?'),
  'stone_intents': ('Kullanılabileceği niyetler', 'Intents it suits'),
  'previous': ('Önceki', 'Previous'),
  'next': ('Sonraki', 'Next'),
  'return_moment': ('Dönüş anı', 'Return moment'),
  'choose_spread': ('Açılımını seç', 'Choose a spread'),
  'spread_theme_general': ('Genel', 'General'),
  'spread_theme_love': ('Aşk', 'Love'),
  'spread_theme_relationship': ('İlişki', 'Relationship'),
  'spread_theme_career': ('Kariyer', 'Career'),
  'spread_theme_money': ('Para', 'Money'),
  'spread_theme_spiritual': ('Ruhsal', 'Spiritual'),
  'question_required': ('Sorun (gerekli)', 'Your question (required)'),
  'question_hint': (
    'Aklındaki soruyu açık bir şekilde yaz',
    'Write the question on your mind clearly',
  ),
  'question_too_short': (
    'Bu açılım için sorunu yaz.',
    'This spread needs your question.',
  ),
  'shuffling': ('Kartlar karıştırılıyor…', 'Shuffling…'),
  'premium': ('Premium', 'Premium'),
  'unlock_premium': ('Planları incele', 'Explore plans'),
  'combined_reading': ('Birleşik Yorum', 'The Reading as a Whole'),
  'deepen_with_ai': ('Astro AI ile Derinleştir', 'Deepen with Astro AI'),
  'deepen_note': (
    'Tüm kartlar ve pozisyonları Astro AI\'ye gönderilir; yorum kartları değiştirmez.',
    'Every card and its position is sent to Astro AI; the interpretation never changes the draw.',
  ),
  'new_reading': ('Yeniden Açılım Yap', 'Do a new reading'),
  'shuffle_cards': ('Kartları Karıştır', 'Shuffle the cards'),
  'shuffle_runes': ('Rünleri Karıştır', 'Shuffle the runes'),
  'shuffling_runes': ('Rünler karıştırılıyor…', 'Shuffling the runes…'),
  'pick_intro_cards': (
    'Kartlar kapalı. İçinden gelenleri sırayla seç: ilk seçtiğin ilk pozisyona gider.',
    'The cards are face down. Pick the ones that call you, in order: your first pick fills the first position.',
  ),
  'pick_intro_runes': (
    'Rünler kesede, sembolleri gizli. İçinden gelenleri sırayla seç: ilk seçtiğin ilk pozisyona gider.',
    'The runes are in the bag, symbols hidden. Pick the ones that call you, in order: your first pick fills the first position.',
  ),
  'selected_count_cards': ('{x} / {n} kart seçildi', '{x} / {n} cards chosen'),
  'selected_count_runes': ('{x} / {n} rün seçildi', '{x} / {n} runes chosen'),
  'selection_waiting': ('seçim bekleniyor', 'waiting for a pick'),
  'position_picked': ('seçildi', 'picked'),
  'reading_title': ('AI Uyum Yorumu', 'AI Compatibility Reading'),
  'reading_kind_synastry': (
    'Sinastri: iki kişinin birbirini nasıl etkilediği',
    'Synastry: how the two of you affect each other',
  ),
  'reading_kind_composite': (
    'Composite: ilişkinin kendisi, ayrı bir bütün olarak',
    'Composite: the relationship itself, as its own whole',
  ),
  'reading_kind_davison': (
    'Davison: ilişkinin zaman ve mekân temelli ortak haritası',
    'Davison: the shared chart of the relationship in time and place',
  ),
  'reading_loading': (
    'Astro AI hesaplanan haritayı yorumluyor…',
    'Astro AI is reading the calculated charts…',
  ),
  'reading_failed': (
    'Yorum şu an oluşturulamadı. Astrolojik hesaplama aşağıda.',
    'The reading could not be prepared right now. The calculation is below.',
  ),
  'reading_ai_off': (
    'Astro AI bu sunucuda kapalı. Astrolojik hesaplama aşağıda.',
    'Astro AI is not enabled on this server. The calculation is below.',
  ),
  'reading_unavailable': (
    'Bu hesaplama için yorum istenemiyor. Astrolojik hesaplama aşağıda.',
    'A reading cannot be requested for this calculation. The calculation is below.',
  ),
  'reading_factors': (
    'Bu yorumu oluşturan etkiler',
    'The factors behind this reading',
  ),
  'reading_section_overview': (
    'İlişkinizin Genel Dinamiği',
    'Your Relationship Dynamic',
  ),
  'reading_section_love': ('Aşk ve Çekim', 'Love and Attraction'),
  'reading_section_communication': ('İletişim', 'Communication'),
  'reading_section_emotional': ('Duygusal Bağ', 'Emotional Bond'),
  'reading_section_passion': (
    'Tutku ve Fiziksel Çekim',
    'Passion and Physical Chemistry',
  ),
  'reading_section_challenges': ('Zorlayıcı Alanlar', 'Challenging Areas'),
  'reading_section_strengths': (
    'İlişkinin Güçlü Tarafları',
    'Strengths of the Relationship',
  ),
  'reading_section_long_term': ('Uzun Vadeli Dinamik', 'Long-Term Dynamic'),
  'reading_section_summary': ('Astro AI Özeti', 'Astro AI Summary'),
  'factor_theme_scores': ('Tema puanları', 'Theme scores'),
  'factor_chart_summary': ('Harita özeti', 'Chart summary'),
  'technical_details': (
    'Teknik Astroloji Detayları',
    'Technical Astrology Details',
  ),
  'tech_index': ('Astrolojik faktör indeksi', 'Astrological factor index'),
  'tech_themes': ('Temalar', 'Themes'),
  'tech_aspects': ('Açılar', 'Aspects'),
  'tech_overlays': ('Ev bindirmeleri', 'House overlays'),
  'tech_planets': ('Gezegenler', 'Planets'),
  'tech_houses': ('Evler', 'Houses'),
  'tech_angles': ('Köşe noktaları', 'Angles'),
  'tech_midpoint': ('Zaman orta noktası (UTC)', 'Time midpoint (UTC)'),
  'tech_engine': ('Hesaplama bilgisi', 'Calculation info'),
  'house_n': ('{n}. ev', 'house {n}'),
  'angle_asc': ('Yükselen', 'Ascendant'),
  'angle_dsc': ('Alçalan', 'Descendant'),
  'angle_mc': ('MC', 'MC'),
  'angle_ic': ('IC', 'IC'),
  'rel_theme_general': ('Genel', 'General'),
  'rel_theme_emotional': ('Duygusal', 'Emotional'),
  'rel_theme_communication': ('İletişim', 'Communication'),
  'rel_theme_romance': ('Romantizm', 'Romance'),
  'rel_theme_sexual_chemistry': ('Fiziksel çekim', 'Physical chemistry'),
  'rel_theme_trust': ('Güven', 'Trust'),
  'rel_theme_long_term': ('Uzun vade', 'Long term'),
  'rel_theme_conflict': ('Çatışma', 'Conflict'),
  'rel_theme_karmic': ('Karmik', 'Karmic'),
  'plans_title': ('Planlar ve AstroCoin', 'Plans and AstroCoin'),
  'plans_headline': (
    'Gökyüzünü kendi hızında keşfet',
    'Explore the sky at your own pace',
  ),
  'plans_verified_note': (
    'Plan ve bakiyen sunucu tarafından doğrulanır; fiyatlar mağazadan gelir.',
    'Your plan and balance are verified by the server; prices come from the store.',
  ),
  'plan_checking': ('Erişim kontrol ediliyor', 'Checking access'),
  'plan_current': ('Mevcut plan', 'Current plan'),
  'plan_until': ('Erişim bitişi', 'Access until'),
  'plan_grace': (
    'Ödeme yenileniyor; erişimin ek süre boyunca açık.',
    'Payment is being retried; access stays open during the grace period.',
  ),
  'plan_cancelled_until': (
    'İptal edildi; bitiş tarihine kadar aktif.',
    'Cancelled; active until the end date.',
  ),
  'plan_expired': ('Planın süresi doldu.', 'Your plan has expired.'),
  'plan_error': ('Erişim doğrulanamadı.', 'Access could not be verified.'),
  'plan_yours': ('Planın', 'Your plan'),
  'plan_best': ('En kapsamlı', 'Most complete'),
  'plan_monthly': ('Aylık', 'Monthly'),
  'plan_yearly': ('Yıllık', 'Yearly'),
  'tier_free': ('Ücretsiz', 'Free'),
  'tier_premium': ('Premium', 'Premium'),
  'tier_cosmic_plus': ('Kozmik+', 'Cosmic+'),
  'plan_free_daily': (
    'Günlük temel astroloji içerikleri · günde {draws} Tarot/Rune/Katina',
    'Daily astrology basics · {draws} Tarot/Rune/Katina a day',
  ),
  'plan_free_ads': (
    'Reklam izleyerek AstroCoin kazan, coin ile bazı içerikleri aç',
    'Earn AstroCoins by watching ads, unlock some content with coins',
  ),
  'plan_premium_daily': (
    'Günde {draws} Tarot/Rune/Katina ve gelişmiş açılımlar · her ay {coins} bonus coin',
    '{draws} Tarot/Rune/Katina a day and advanced spreads · {coins} bonus coins every month',
  ),
  'plan_cosmic_everything': (
    'Premium\'daki her şey · günde {draws} açılım · her ay {coins} bonus coin',
    'Everything in Premium · {draws} readings a day · {coins} bonus coins every month',
  ),
  'plan_ad_free': ('Reklamsız kullanım', 'Ad-free'),
  'plan_monthly_forecast': ('Aylık öngörü', 'Monthly forecast'),
  'plan_advanced_transits': (
    'Daha detaylı transitler',
    'More detailed transits',
  ),
  'plan_relationships': (
    'Sinastri, Composite ve Davison',
    'Synastry, Composite and Davison',
  ),
  'plan_yearly_forecast': ('Yıllık öngörü', 'Yearly forecast'),
  'plan_returns': ('Solar ve Lunar Return', 'Solar and Lunar Return'),
  'plan_advanced_ai': ('Gelişmiş Astro AI', 'Advanced Astro AI'),
  'plan_reports': ('Özel raporlar planına dahil', 'Special reports included'),
  'buy': ('Satın al', 'Buy'),
  'restore_purchases': ('Satın alımları geri yükle', 'Restore purchases'),
  'purchase_pending': (
    'Satın alma beklemede. Sunucu doğrulayana kadar erişim açılmaz.',
    'Purchase pending. Access opens once the server verifies it.',
  ),
  'purchase_cancelled': ('Satın alma iptal edildi.', 'Purchase cancelled.'),
  'store_unavailable_note': (
    'Mağaza ürünleri bu ortamda kullanılamıyor. Fiyat veya ödeme bilgisi gösterilemiyor.',
    'Store products are not available here. No price or payment can be shown.',
  ),
  'coin_packs_title': ('AstroCoin paketleri', 'AstroCoin packs'),
  'coin_packs_note': (
    'Coin; ek açılımlar, gelişmiş açılımlar ve özel içerikler için kullanılır.',
    'Coins pay for extra readings, advanced spreads and special content.',
  ),
  'coin_wallet': ('AstroCoin Cüzdanı', 'AstroCoin Wallet'),
  'coins_unit': ('coin', 'coins'),
  'coin_balance': ('Bakiyen', 'Your balance'),
  'coin_bonus_granted': (
    'Bu ayın bonusu eklendi: +{coins}',
    'This month\'s bonus added: +{coins}',
  ),
  'coin_monthly_bonus': (
    'Planın her ay {coins} bonus coin ekler.',
    'Your plan adds {coins} bonus coins every month.',
  ),
  'coin_monthly_bonus_upgrade': (
    'Premium ve Kozmik+ her ay bonus coin kazandırır.',
    'Premium and Cosmic+ add bonus coins every month.',
  ),
  'coin_earn': ('Coin kazan', 'Earn coins'),
  'coin_watch_ad': (
    'Reklam izle, +{coins} coin',
    'Watch an ad, +{coins} coins',
  ),
  'coin_ads_left': (
    'Bugün kalan: {left} / {limit}',
    'Left today: {left} / {limit}',
  ),
  'coin_ads_off': (
    'Ödüllü reklamlar şu an kullanılamıyor.',
    'Rewarded ads are not available right now.',
  ),
  'coin_ads_paid_plan': (
    'Planın reklamsız; coin kazanmak için aylık bonusun ve paketler var.',
    'Your plan is ad-free; you have the monthly bonus and packs.',
  ),
  'coin_ad_rewarded': (
    '+{coins} coin hesabına eklendi.',
    '+{coins} coins added.',
  ),
  'coin_ad_closed': (
    'Reklam tamamlanmadı; coin eklenmedi.',
    'The ad was not completed; no coins added.',
  ),
  'coin_ad_limit': (
    'Bugünkü reklam hakların doldu.',
    'Today\'s rewarded ads are used up.',
  ),
  'coin_ad_unavailable': (
    'Ödüllü reklamlar şu an kullanılamıyor.',
    'Rewarded ads are not available right now.',
  ),
  'coin_buy_packs': ('Coin paketi al', 'Buy a coin pack'),
  'coin_spend_title': ('Coin ile neler açılır', 'What coins unlock'),
  'coming_soon': ('Yakında', 'Soon'),
  'spend_extra_draw': (
    'Günlük hakkın bittiğinde ek açılım',
    'An extra reading after the daily allowance',
  ),
  'spend_advanced_spread': (
    'Planında olmayan gelişmiş bir açılım',
    'An advanced spread outside your plan',
  ),
  'spend_ai_deep_reading': ('Astro AI derin yorum', 'Astro AI deep reading'),
  'spend_special_analysis': ('Özel analiz', 'Special analysis'),
  'spend_single_premium_content': (
    'Tek seferlik premium içerik',
    'One-time premium content',
  ),
  'coin_history': ('Hareket geçmişi', 'History'),
  'coin_history_empty': ('Henüz coin hareketi yok.', 'No coin activity yet.'),
  'coin_kind_purchase': ('Coin paketi', 'Coin pack'),
  'coin_kind_ad_reward': ('Reklam ödülü', 'Ad reward'),
  'coin_kind_monthly_bonus': ('Aylık plan bonusu', 'Monthly plan bonus'),
  'coin_kind_spend': ('Harcama', 'Spent'),
  'coin_kind_refund': ('İade', 'Refund'),
  'coin_kind_purchase_reversal': ('Paket iadesi', 'Pack refunded'),
  'coin_offer_title_extra_draw': (
    'Bugünkü açılım hakların doldu',
    'Today\'s readings are used up',
  ),
  'coin_offer_title_advanced_spread': (
    'Bu açılım planında yok',
    'This spread is not in your plan',
  ),
  'coin_offer_body': (
    '{price} AstroCoin ile devam edebilirsin. Bakiyen: {balance} coin.',
    'You can continue for {price} AstroCoins. Balance: {balance} coins.',
  ),
  'coin_offer_pay': ('{price} coin ile devam et', 'Continue for {price} coins'),
  'coin_offer_plans': ('Planlar', 'Plans'),
  'coin_offer_earn': ('Coin kazan', 'Earn coins'),
  'coin_open_spread': ('{price} coin ile aç', 'Open for {price} coins'),
  'draws_left': (
    'Bugün kalan açılım: {left} / {limit}',
    'Readings left today: {left} / {limit}',
  ),
  'draws_none_left': (
    'Bugünkü hakların doldu · ek açılım {price} coin',
    'Today\'s readings are used · extra reading {price} coins',
  ),
  'hub_spreads_sub': (
    'Kartını seç, sezgine kulak ver',
    'Pick your cards, listen to your intuition',
  ),
  'hub_tarot_sub': ('78 kart', '78 cards'),
  'hub_rune_sub': ('24 kadim rün', '24 ancient runes'),
  'hub_katina_sub': ('Aşk ve ilişki', 'Love and relationships'),
  'hub_consultants': ('Danışmanlarla Görüş', 'Talk to a Consultant'),
  'hub_consultants_sub': (
    'Astrolog, Tarot, Rune ve Katina danışmanları',
    'Astrologers, Tarot, Rune and Katina readers',
  ),
  'hub_see_all': ('Tümünü gör', 'See all'),
  'hub_consultants_empty': (
    'Şu an öne çıkan danışman yok.',
    'No featured consultants right now.',
  ),
  'hub_consultants_error': (
    'Danışmanlar yüklenemedi.',
    'Consultants could not be loaded.',
  ),
  'hub_new_expert': ('Yeni', 'New'),
  'hub_from_price': ('{price}’den', 'from {price}'),
  'experts_katina': ('Katina Danışmanları', 'Katina Readers'),
  'hub_services': ('Hizmet Türleri', 'Ways to Consult'),
  'hub_services_sub': (
    'Sana uygun görüşme biçimini seç',
    'Choose how you want to talk',
  ),
  'hub_service_chat': ('Yazışarak danış', 'Chat'),
  'hub_service_chat_sub': (
    'Mesajlaşarak, kendi hızında',
    'By message, at your own pace',
  ),
  'hub_service_voice': ('Sesli görüşme', 'Voice call'),
  'hub_service_voice_sub': ('Canlı, sesli seans', 'A live voice session'),
  'hub_service_video': ('Görüntülü görüşme', 'Video call'),
  'hub_service_video_sub': (
    'Yüz yüze, görüntülü seans',
    'A face-to-face video session',
  ),
  'hub_service_written_report': ('Yazılı analiz', 'Written analysis'),
  'hub_service_written_report_sub': (
    'Detaylı, yazılı rapor',
    'A detailed written report',
  ),
  'hub_appointments': ('Randevularım', 'My Appointments'),
  'hub_appointments_none': (
    'Yaklaşan randevun yok · geçmiş randevuların burada',
    'No upcoming appointments · your past ones are here',
  ),
  'hub_appointments_next': (
    'Sıradaki: {when} · {count} yaklaşan',
    'Next: {when} · {count} upcoming',
  ),
  'hub_plans_title': ('Planlar ve AstroCoin', 'Plans and AstroCoin'),
  'hub_plans_sub': (
    'Premium, Kozmik+ ve coin paketleri',
    'Premium, Cosmic+ and coin packs',
  ),
  'specialty_astrology': ('Astroloji', 'Astrology'),
  'specialty_natal_chart': ('Doğum haritası', 'Natal chart'),
  'specialty_transits': ('Transitler', 'Transits'),
  'specialty_synastry': ('Sinastri', 'Synastry'),
  'specialty_composite': ('Composite', 'Composite'),
  'specialty_davison': ('Davison', 'Davison'),
  'specialty_horary': ('Soru astrolojisi', 'Horary'),
  'specialty_monthly_forecast': ('Aylık öngörü', 'Monthly forecast'),
  'specialty_annual_forecast': ('Yıllık öngörü', 'Yearly forecast'),
  'specialty_tarot': ('Tarot', 'Tarot'),
  'specialty_rune': ('Rune', 'Rune'),
  'specialty_katina': ('Katina', 'Katina'),
  'profile_customize': ('Profili özelleştir', 'Customise profile'),
  'profile_avatar': ('Avatar', 'Avatar'),
  'profile_display_name': ('Görünen ad', 'Display name'),
  'profile_bio': ('Kısa bio', 'Short bio'),
  'profile_bio_hint': (
    'Kendini birkaç kelimeyle anlat',
    'Describe yourself in a few words',
  ),
  'profile_cover': ('Kapak teması', 'Cover theme'),
  'profile_language': ('Tercih edilen dil', 'Preferred language'),
  'profile_notifications': ('Bildirim tercihleri', 'Notification preferences'),
  'profile_privacy': ('Gizlilik', 'Privacy'),
  'cover_cosmic_night': ('Kozmik gece', 'Cosmic night'),
  'cover_golden_dawn': ('Altın şafak', 'Golden dawn'),
  'cover_moonlit': ('Ay ışığı', 'Moonlit'),
  'cover_nebula': ('Nebula', 'Nebula'),
  'cover_aurora': ('Aurora', 'Aurora'),
  'big3_sun': ('Güneş', 'Sun'),
  'big3_moon': ('Ay', 'Moon'),
  'big3_rising': ('Yükselen', 'Rising'),
  'notifications_device_permission': (
    'Cihaz bildirim iznini aç',
    'Allow notifications on this device',
  ),
  'notifications_intro': (
    'Hangi bildirimleri almak istediğini seç. Gelen arama ve ödeme bildirimleri güvenlik için her zaman açıktır. Cihaz izni ayrıca istenir.',
    'Choose what you want to be notified about. Incoming calls and payment notices always stay on. Device permission is asked separately.',
  ),
  'notification_prefs_daily_horoscope': (
    'Günlük içerik ve burç yorumu',
    'Daily content and horoscope',
  ),
  'notification_prefs_transit_alerts': (
    'Önemli transitler',
    'Important transits',
  ),
  'notification_prefs_moon_phases': ('Ay evreleri', 'Moon phases'),
  'notification_prefs_ai_reports': (
    'Astro AI yorumu / rapor hazır',
    'Astro AI reading / report ready',
  ),
  'notification_prefs_expert_messages': (
    'Danışman mesajları',
    'Messages from consultants',
  ),
  'notification_prefs_appointment_reminders': (
    'Randevu bildirimleri ve hatırlatmaları',
    'Appointment updates and reminders',
  ),
  'notification_prefs_promotions': (
    'Kampanya ve yenilikler',
    'Offers and news',
  ),
  'privacy_intro': (
    'Profilinin gösterildiği yerlerde (ör. danışmanlarla) neyin görüneceğini seç.',
    'Choose what is shown where your profile appears (e.g. to consultants).',
  ),
  'privacy_show_sun_sign': ('Güneş burcumu göster', 'Show my sun sign'),
  'privacy_show_moon_sign': ('Ay burcumu göster', 'Show my moon sign'),
  'privacy_show_rising_sign': ('Yükselenimi göster', 'Show my rising sign'),
  'privacy_show_birth_date': ('Doğum tarihimi göster', 'Show my birth date'),
  'privacy_show_bio': ('Bio metnimi göster', 'Show my bio'),
  'section_failed': (
    'Bu bölüm yüklenemedi.',
    'This section could not be loaded.',
  ),
  'angles_unavailable': (
    'Doğum saati veya yeri bilinmediği için yükselen, MC ve evler hesaplanamadı.',
    'Without a birth time and place, the ascendant, MC and houses cannot be calculated.',
  ),
  'missing_birth_data': (
    'Bu hesaplama için doğum tarihi, saati ve yeri gerekli.',
    'This calculation needs a birth date, time and place.',
  ),
  'scroll_hint': (
    'Kaydırarak {n} kartın tümünü gör',
    'Swipe to see all {n} cards',
  ),
  'selection_complete': ('Seçimin tamamlandı', 'Your selection is complete'),
  'reveal_cards': ('Kartları Aç', 'Reveal the cards'),
  'reveal_runes': ('Rünleri Aç', 'Reveal the runes'),
  'revealing': ('Seçtiğin kartlar açılıyor', 'Revealing your picks'),
  'face_down_cards': ('Kapalı kart {n}', 'Face-down card {n}'),
  'face_down_runes': ('Kapalı rün {n}', 'Face-down rune {n}'),
  'picked_as': ('{n}. seçim', 'pick {n}'),
  'change_spread': ('Açılımı değiştir', 'Change spread'),
  'reshuffle': ('Yeniden karıştır', 'Shuffle again'),
  'divination_session_expired': (
    'Bu karıştırmanın süresi doldu. Yeniden karıştırıp tekrar seç.',
    'This shuffle has expired. Shuffle again and pick anew.',
  ),
  'session_already_completed': (
    'Bu açılım zaten başka bir seçimle açıldı.',
    'This spread was already revealed with a different selection.',
  ),
  'card_meaning': ('Temel anlam', 'Core meaning'),
  'spread_meaning_love': ('Aşk bağlamında', 'In love'),
  'spread_meaning_relationship': ('İlişki bağlamında', 'In the relationship'),
  'spread_meaning_career': ('Kariyer bağlamında', 'At work'),
  'spread_meaning_money': ('Maddi bağlamda', 'In material matters'),
  'spread_meaning_spiritual': ('Ruhsal bağlamda', 'On the inner path'),
  'shadow_side': ('Gölge yönü', 'Shadow side'),
  'symbolism': ('Sembolizm', 'Symbolism'),
  'premium_required': (
    'Bu özellik daha üst bir plana dahil; tek kullanım seçeneklerini de inceleyebilirsin.',
    'This feature is included in a higher plan; you can also check one-time options.',
  ),
  'natal': ('Doğum Haritam', 'My Natal Chart'),
  'transits': ('Transitler', 'Transits'),
  'calendar': ('Kozmik Takvim', 'Cosmic Calendar'),
  'daily': ('Günlük', 'Daily'),
  'weekly': ('Haftalık', 'Weekly'),
  'monthly': ('Aylık', 'Monthly'),
  'yearly': ('Yıllık', 'Yearly'),
  'forecasts': ('Gökyüzü Öngörüleri', 'Sky Forecasts'),
  'frequency': ('Bugünün Frekansı', 'Daily Frequency'),
  'horary': ('Soru Astrolojisi', 'Horary'),
  'compatibility': ('Uyum Analizi', 'Compatibility'),
  'synastry': ('Sinastri', 'Synastry'),
  'composite': ('Composite', 'Composite'),
  'davison': ('Davison', 'Davison'),
  'saved_people': ('Kaydedilen Kişiler', 'Saved People'),
  'profile_edit': ('Hesap ve Doğum Bilgileri', 'Account and Birth Data'),
  'loading': ('Gökyüzün hazırlanıyor…', 'Preparing your sky…'),
  'empty': ('Henüz kayıt yok.', 'No records yet.'),
  'retry': ('Tekrar dene', 'Try again'),
  'back': ('Geri', 'Back'),
  'save': ('Kaydet', 'Save'),
  'create': ('Oluştur', 'Create'),
  'delete': ('Sil', 'Delete'),
  'cancel': ('Vazgeç', 'Cancel'),
  'confirm_delete': ('Bu kaydı silmek istiyor musun?', 'Delete this record?'),
  'demo_unavailable': (
    'Bu bölümün gerçek verileri API modunda kullanılabilir.',
    'Real data for this section is available in API mode.',
  ),
  'network': (
    'Bağlantı kurulamadı. İnternet bağlantını kontrol et.',
    'Connection failed. Check your internet connection.',
  ),
  'timeout': (
    'İstek zaman aşımına uğradı. İşlem geçmişini kontrol et.',
    'The request timed out. Check your history before submitting again.',
  ),
  'unauthorized': (
    'Oturumun sona erdi. Yeniden giriş yap.',
    'Your session expired. Sign in again.',
  ),
  'not_found': (
    'Kayıt bulunamadı veya erişimin yok.',
    'This record is unavailable or not yours.',
  ),
  'validation': (
    'Bilgileri kontrol et. Tarih, saat ve konum geçerli olmalı.',
    'Check the date, time and location values.',
  ),
  'rate_limited': (
    'İstek sınırına ulaşıldı. Bir süre sonra yeniden dene.',
    'Request limit reached. Try again later.',
  ),
  'ai_not_configured': (
    'Astro AI bu ortamda henüz yapılandırılmamış.',
    'Astro AI is not configured in this environment.',
  ),
  'firebase_not_configured': (
    'Firebase bağlantısı yapılandırılmamış. Ortam ayarları gerekli.',
    'Firebase is not configured. Environment setup is required.',
  ),
  'provider_unavailable': (
    'Hizmet şu anda kullanılamıyor. Daha sonra yeniden dene.',
    'The service is temporarily unavailable.',
  ),
  'error': (
    'İşlem tamamlanamadı. Lütfen daha sonra yeniden dene.',
    'The operation could not be completed. Try again later.',
  ),
  'birth_profile_missing': (
    'Önce doğum bilgilerini tamamla.',
    'Complete your birth data first.',
  ),
  'sources': ('Bu yorumu oluşturan etkiler', 'Factors behind this reading'),
  'available_sources': (
    'Yorum için mevcut kaynaklar',
    'Available context factors',
  ),
  'warnings': ('Dikkat edilmesi gerekenler', 'Notes and limitations'),
  'engine': ('Hesaplama bilgileri', 'Engine metadata'),
  'planets': ('Gezegenler', 'Planets'),
  'houses': ('Evler ve yöneticileri', 'Houses and rulers'),
  'aspects': ('Açılar', 'Aspects'),
  'angles': ('Köşe noktaları', 'Angles'),
  'passes': ('Kesinleşme geçişleri', 'Exact passes'),
  'clipped': (
    'Tarihler arama sınırıdır; kesin başlangıç/bitiş değildir.',
    'Dates are search bounds, not exact start/end times.',
  ),
  'ingresses': ('Ev geçişleri', 'House ingresses'),
  'hours': ('Önemli saatler', 'Important hours'),
  'index_note': (
    'Astrolojik faktör indeksi; başarı olasılığı veya yüzde değildir.',
    'Astrological factor index; not a success probability or percentage.',
  ),
  'question': ('Sorun', 'Your question'),
  'location': ('Konum', 'Location'),
  'latitude': ('Enlem', 'Latitude'),
  'longitude': ('Boylam', 'Longitude'),
  'timezone': ('Saat dilimi (Europe/Istanbul)', 'Time zone (Europe/Istanbul)'),
  'name': ('Ad', 'Name'),
  'date': ('Doğum tarihi (YYYY-MM-DD)', 'Birth date (YYYY-MM-DD)'),
  'time': (
    'Doğum saati (HH:mm, bilinmiyorsa boş)',
    'Birth time (HH:mm, blank if unknown)',
  ),
  'calculate': ('Hesapla', 'Calculate'),
  'birth_date_label': ('Doğum tarihi', 'Birth date'),
  'birth_date_required': ('Doğum tarihini seç.', 'Choose a birth date.'),
  'birth_time_label': ('Doğum saati', 'Birth time'),
  'birth_time_unknown': ('Bilinmiyor', 'Unknown'),
  'birth_time_unknown_toggle': (
    'Doğum saatimi bilmiyorum',
    'I do not know my birth time',
  ),
  'birth_time_unknown_note': (
    'Saat olmadan evler, yükselen ve MC hesaplanamaz; gezegen burçları hesaplanır.',
    'Without a time, houses, Ascendant and MC cannot be calculated; planet signs still are.',
  ),
  'birth_place_label': ('Doğum yeri', 'Birth place'),
  'birth_place_hint': ('Şehir ara, ör. İzmir', 'Search a city, e.g. Izmir'),
  'birth_place_required': (
    'Doğum yerini ara ve listeden seç.',
    'Search your birth place and pick it from the list.',
  ),
  'manual_coordinates': (
    'Koordinatları elle gir',
    'Enter coordinates manually',
  ),
  'analysis': ('Analiz', 'Analysis'),
  'no_verdict': (
    'Bu analiz kesin evet/hayır yanıtı üretmez.',
    'This analysis does not produce a yes/no verdict.',
  ),
  'significators': ('Göstergeler', 'Significators'),
  'moon': ('Ay', 'Moon'),
  'receptions': ('Resepsiyonlar', 'Receptions'),
  'dignities': ('Asaletler', 'Dignities'),
  'perfection': ('Tamamlanma faktörleri', 'Perfection factors'),
  'obstructions': ('Engelleyici faktörler', 'Obstruction factors'),
  'not_implemented': ('Hesaplanmayan teknikler', 'Techniques not evaluated'),
  'themes': ('İlişki temaları', 'Relationship themes'),
  'overlays': ('Karşılıklı ev yerleşimleri', 'Directional house overlays'),
  'positive': ('Destekleyici', 'Supportive'),
  'challenging': ('Zorlayıcı', 'Challenging'),
  'ambiguous': ('Belirsiz orta noktalar', 'Ambiguous midpoints'),
  'draw': ('Kart çek', 'Draw'),
  'tarot': ('Tarot', 'Tarot'),
  'rune': ('Rune', 'Rune'),
  'katina': ('Katina', 'Katina'),
  'interpret': ('AI yorumu iste', 'Request AI interpretation'),
  'history': ('Geçmiş', 'History'),
  'reversed': ('Ters', 'Reversed'),
  'upright': ('Düz', 'Upright'),
  'optional_rune': (
    'Modern ekleme: Odin boş taşı',
    'Modern addition: blank Odin rune',
  ),
  'reports': ('Astro AI Raporları', 'Astro AI Reports'),
  'conversations': ('Sohbetler', 'Conversations'),
  'queued': ('Sırada', 'Queued'),
  'running': ('Hazırlanıyor', 'Running'),
  'completed': ('Tamamlandı', 'Completed'),
  'failed': ('Tamamlanamadı', 'Failed'),
  'cancelled': ('İptal edildi', 'Cancelled'),
  'partial': ('Yanıt tamamlanmadı', 'Incomplete response'),
  'unknown': ('Bilinmeyen durum', 'Unknown state'),
  'stop': ('Durdur', 'Stop'),
  'facts_note': (
    'Hesaplanan veriler • AI yorumu değildir',
    'Computed facts • not AI prose',
  ),
  'update_unsupported': (
    'Mevcut API kayıt güncellemeyi desteklemiyor.',
    'The current API does not support editing saved people.',
  ),
  'saved': ('Kaydedildi', 'Saved'),
  'periods': ('Önemli dönemler', 'Key periods'),
  'marketplace': ('Canlı Danışmanlık', 'Expert Marketplace'),
  'expert_detail': ('Danışman Profili', 'Expert Profile'),
  'services': ('Hizmetler', 'Services'),
  'favorites': ('Favori Danışmanlar', 'Favorite Experts'),
  'reviews': ('Değerlendirmeler', 'Reviews'),
  'verified': ('Doğrulanmış danışman', 'Verified expert'),
  'rating': ('Puan', 'Rating'),
  'search_page': (
    'Bu sayfadaki danışmanlarda ara',
    'Search experts on this page',
  ),
  'filters': ('Filtreler', 'Filters'),
  'specialty': ('Uzmanlık', 'Specialty'),
  'language': ('Dil', 'Language'),
  'delivery': ('Görüşme türü', 'Delivery type'),
  'sort': ('Sıralama', 'Sort'),
  'price_range': ('Fiyat aralığı (TRY)', 'Price range (TRY)'),
  'load_more': ('Daha fazla yükle', 'Load more'),
  'select_service': ('Hizmet seç', 'Select service'),
  'slots': ('Uygun Saatler', 'Available Slots'),
  'slot_unavailable': (
    'Bu saat artık uygun değil. Liste yenilendi.',
    'This slot is no longer available. Times have been refreshed.',
  ),
  'booking': ('Randevu Oluştur', 'Book an Appointment'),
  'orders': ('Siparişlerim', 'My Orders'),
  'order_detail': ('Sipariş Detayı', 'Order Details'),
  'appointments': ('Randevularım', 'My Appointments'),
  'appointment_detail': ('Randevu Detayı', 'Appointment Details'),
  'payment_required': ('Ödeme gerekli', 'Payment required'),
  'payment_unavailable': (
    'Ödeme işlemi şu anda kullanılamıyor.',
    'Payment is unavailable right now.',
  ),
  'consent': ('Veri Paylaşım İzinleri', 'Data Sharing Consent'),
  'consent_note': (
    'Bu danışmanla paylaşacağınız veriler. Sohbet açmak paylaşım izni vermez.',
    'Data you share with this expert. Opening chat does not grant consent.',
  ),
  'review_eligible': (
    'Bu tamamlanan görüşmeyi değerlendir',
    'Review this completed consultation',
  ),
  'chat_unavailable': (
    'Bu görüşme için sohbet kullanılamıyor.',
    'Chat is unavailable for this consultation.',
  ),
  'chat_open_note': (
    'Sohbet uygunluğu sipariş ve hizmet durumuna göre kontrol edilir.',
    'Chat eligibility is checked against the order and service.',
  ),
  'open_chat': ('Sohbeti Aç', 'Open chat'),
  'chat_read_only': (
    'Bu sohbet yalnız okunabilir.',
    'This conversation is read-only.',
  ),
  'idempotency_conflict': (
    'İstek daha önce farklı içerikle gönderildi. İşlem geçmişini kontrol et.',
    'This request conflicts with an earlier submission. Check your history.',
  ),
  'attachment_invalid': (
    'Yalnız JPG, PNG veya WebP; en fazla 8 MiB.',
    'Use JPG, PNG or WebP up to 8 MiB.',
  ),
  'attachment_not_ready': (
    'Görsel henüz hazır değil; mesaj gönderilmedi.',
    'The image is not ready; no message was sent.',
  ),
  'message': ('Mesaj', 'Message'),
  'send': ('Gönder', 'Send'),
  'read_only': ('Yalnız Okunabilir', 'Read-only'),
  'closed': ('Kapalı', 'Closed'),
  'suspended': ('Askıda', 'Suspended'),
  'consultations': ('Danışman Sohbetleri', 'Consultation Chats'),
  'typing': ('Yazıyor…', 'Typing…'),
  'online': ('Çevrimiçi', 'Online'),
  'offline': ('Çevrimdışı', 'Offline'),
  'uploading': ('Görsel yükleniyor', 'Uploading image'),
  'image_attachment': ('Görsel', 'Image'),
  'file_attachment': ('Dosya eki', 'File attachment'),
  'message_deleted': ('Mesaj silindi', 'Message deleted'),
  'notification_permission': (
    'Randevu ve mesaj bildirimleri için izin ver',
    'Enable appointment and message notifications',
  ),
  'expert_workspace': ('Danışman Çalışma Alanı', 'Expert Workspace'),
  // ---- coin spending
  'coin_word': ('Coin', 'Coins'),
  'coin_confirm_title': ('AstroCoin ile aç', 'Unlock with AstroCoins'),
  'coin_confirm_body': (
    '{item}: {price} AstroCoin. Bakiyen: {balance} coin. İşlem başarısız olursa coin iade edilir.',
    '{item}: {price} AstroCoins. Balance: {balance} coins. A failed request is refunded.',
  ),
  'coin_confirm_pay': ('{price} Coin ile aç', 'Unlock for {price} coins'),
  'coin_short_title': ('Yetersiz AstroCoin', 'Not enough AstroCoins'),
  'coin_short_body': (
    '{item} {price} coin; bakiyen {balance}. Cüzdanından coin alabilir ya da planını yükseltebilirsin.',
    '{item} costs {price} coins; you have {balance}. Get coins in your wallet or upgrade your plan.',
  ),
  'coin_get_more': ('Cüzdana git', 'Go to wallet'),
  'coin_unlock_once': (
    'Tek seferlik aç · {price} Coin',
    'Unlock once · {price} coins',
  ),
  'coin_lock_note': (
    'Planına dahil değil. Planını yükseltebilir ya da yalnız bunu AstroCoin ile açabilirsin.',
    'Not in your plan. Upgrade, or unlock just this one with AstroCoins.',
  ),
  'insufficient_coins': (
    'AstroCoin bakiyen yetmiyor. Cüzdanından coin alabilirsin.',
    'Not enough AstroCoins. You can get more in your wallet.',
  ),
  'deepen_included': ('Kozmik+ planına dahil.', 'Included in Cosmic+.'),
  'pay_with_coins_report': ('{price} Coin ile al', 'Get it for {price} coins'),
  // ---- plan comparison
  'cmp_title': ('Planları karşılaştır', 'Compare plans'),
  'cmp_included': ('dahil', 'included'),
  'cmp_coins': ('Coin ile', 'With coins'),
  'cmp_none': ('dahil değil', 'not included'),
  'cmp_note': (
    '"Coin ile" olanlar plan değiştirmeden tek seferlik AstroCoin ile açılır; fiyatlar sunucu kataloğundan gelir.',
    '"With coins" items open once for AstroCoins without changing plans; prices come from the server catalogue.',
  ),
  'cmp_daily_basics': (
    'Günlük burç, Ay, Güneş-Ay-Yükselen',
    'Daily horoscope, Moon, Big Three',
  ),
  'cmp_daily_draws': (
    'Günlük Tarot/Rune/Katina açılımı',
    'Daily Tarot/Rune/Katina readings',
  ),
  'cmp_advanced_spreads': ('Gelişmiş açılımlar', 'Advanced spreads'),
  'cmp_ai_deep_reading': ('Astro AI ile derin yorum', 'Astro AI deep reading'),
  'cmp_monthly_forecast': ('Aylık öngörü', 'Monthly forecast'),
  'cmp_advanced_transits': (
    'Haftalık/aylık transitler',
    'Weekly/monthly transits',
  ),
  'cmp_relationships': (
    'Sinastri, Composite, Davison',
    'Synastry, Composite, Davison',
  ),
  'cmp_yearly_forecast': ('Yıllık öngörü', 'Yearly forecast'),
  'cmp_returns': ('Solar ve Lunar Return', 'Solar and Lunar Return'),
  'cmp_special_reports': (
    'Özel astroloji analizleri',
    'Special astrology analyses',
  ),
  'cmp_ad_free': ('Reklamsız', 'Ad-free'),
  'cmp_monthly_coins': ('Aylık bonus AstroCoin', 'Monthly bonus AstroCoins'),
  'bonus_title': ('Aylık AstroCoin bonusu', 'Monthly AstroCoin bonus'),
  'bonus_yours': (
    'Planın her ay cüzdanına {coins} AstroCoin ekler.',
    'Your plan adds {coins} AstroCoins to your wallet every month.',
  ),
  'bonus_upgrade': (
    'Premium her ay {premium}, Kozmik+ her ay {cosmic} AstroCoin ekler.',
    'Premium adds {premium} and Cosmic+ {cosmic} AstroCoins every month.',
  ),
  'month_word': ('ay', 'month'),
  // ---- wallet sections
  'wallet_earn': ('Coin Kazan', 'Earn Coins'),
  'wallet_buy': ('Coin Satın Al', 'Buy Coins'),
  'wallet_spend': ('Coin Harca', 'Spend Coins'),
  'wallet_recent': ('Son Hareketler', 'Recent Activity'),
  'coin_ads_title': ('Reklamla Coin Kazan', 'Earn Coins with Ads'),
  'coin_ads_soon_note': (
    'Ödüllü reklamlar yakında. Şimdilik aylık bonus ve paketlerle coin kazanabilirsin.',
    'Rewarded ads are coming soon. For now, earn coins with the monthly bonus and packs.',
  ),
  // ---- consultants
  'all_categories': ('Tümü', 'All'),
  'available_today': ('Bugün müsait', 'Available today'),
  'favorites_only': ('Favorilerim', 'My favourites'),
  'verified_short': ('Doğrulanmış', 'Verified'),
  'experts_count': ('{n} danışman', '{n} experts'),
  'experts_empty': (
    'Bu filtrelerle danışman bulunamadı.',
    'No experts match these filters.',
  ),
  'sort_rating': ('Puana göre', 'Top rated'),
  'sort_review_count': ('Yorum sayısı', 'Most reviewed'),
  'sort_price': ('Fiyata göre', 'Lowest price'),
  'sort_experience': ('Deneyime göre', 'Most experienced'),
  'sort_newest': ('En yeni', 'Newest'),
  'lang_tr': ('Türkçe', 'Turkish'),
  'lang_en': ('İngilizce', 'English'),
  'lang_az': ('Azerbaycanca', 'Azerbaijani'),
  'lang_ru': ('Rusça', 'Russian'),
  'lang_de': ('Almanca', 'German'),
  'delivery_chat': ('Yazılı sohbet', 'Chat'),
  'delivery_voice': ('Sesli görüşme', 'Voice call'),
  'delivery_video': ('Görüntülü görüşme', 'Video call'),
  'delivery_written_report': ('Yazılı rapor', 'Written report'),
  'from_price': ('{price}\'den başlayan', 'from {price}'),
  'favorite_toggle': (
    'Favorilere ekle / çıkar',
    'Add to / remove from favourites',
  ),
  'about_expert': ('Hakkında', 'About'),
  'languages': ('Diller', 'Languages'),
  'expert_no_services': (
    'Bu danışmanın şu an aktif hizmeti yok.',
    'This expert has no active services right now.',
  ),
  'book_appointment': ('Randevu Al', 'Book'),
  'no_slots_week': (
    'Önümüzdeki 7 günde uygun saat yok.',
    'No open times in the next 7 days.',
  ),
  'reviews_empty': ('Henüz değerlendirme yok.', 'No reviews yet.'),
  'reviews_word': ('yorum', 'reviews'),
  'experience_years': ('{n} yıl deneyim', '{n} years of experience'),
  'minutes': ('{n} dk', '{n} min'),
  'free_price': ('Ücretsiz', 'Free'),
  'tier_upper_free': ('ÜCRETSİZ', 'FREE'),
  'tier_upper_premium': ('PREMIUM', 'PREMIUM'),
  'tier_upper_cosmic_plus': ('KOZMİK+', 'COSMIC+'),
  // ---- forecast reading
  'fc_intro': (
    'Doğum haritana göre hesaplanan kişisel öngörün.',
    'Your personal forecast, calculated from your birth chart.',
  ),
  'fc_title_daily': ('Günlük Öngörün', 'Your Daily Forecast'),
  'fc_title_weekly': ('Haftalık Öngörün', 'Your Weekly Forecast'),
  'fc_title_monthly': ('Aylık Öngörün', 'Your Monthly Forecast'),
  'fc_title_yearly': ('Yıllık Öngörün', 'Your Yearly Forecast'),
  'fc_tone_label_strong': ('Güçlü Frekans', 'Strong Frequency'),
  'fc_tone_label_balanced': ('Dengeli Frekans', 'Balanced Frequency'),
  'fc_tone_label_demanding': ('Sakin Frekans', 'Quiet Frequency'),
  'fc_tone_strong_general': (
    'Enerjin yüksek; başlatmak ve görünür olmak için elverişli bir dönem.',
    'Your energy is high; a good time to start things and be seen.',
  ),
  'fc_tone_balanced_general': (
    'Dengeli bir dönem; istikrarlı adımlar karşılık bulur.',
    'A balanced period; steady steps pay off.',
  ),
  'fc_tone_demanding_general': (
    'Daha sakin bir dönem; zorlamak yerine önceliklendirmek iyi gelir.',
    'A quieter period; prioritising works better than pushing.',
  ),
  'fc_tone_strong_area': ('Bu alanda akış güçlü.', 'Strong flow in this area.'),
  'fc_tone_balanced_area': (
    'Bu alanda dengeli bir tablo var.',
    'This area looks balanced.',
  ),
  'fc_tone_demanding_area': (
    'Bu alanda zorlayıcı etkiler ağır basıyor; sabırlı olmak iyi gelir.',
    'Challenging influences weigh on this area; patience helps.',
  ),
  'fc_trend_rising': ('Eğilim yükselişte.', 'The trend is rising.'),
  'fc_trend_falling': ('Eğilim düşüşte.', 'The trend is falling.'),
  'fc_sec_general_energy': ('Genel Enerji', 'General Energy'),
  'fc_sec_love': ('Aşk ve İlişkiler', 'Love and Relationships'),
  'fc_sec_career': ('Kariyer', 'Career'),
  'fc_sec_money': ('Para', 'Money'),
  'fc_sec_mood': ('Duygusal Durum', 'Emotional State'),
  'fc_sec_dates': ('Önemli Tarihler', 'Key Dates'),
  'fc_sec_cautions': ('Dikkat Edilecek Konular', 'Things to Watch'),
  'fc_sec_supports': ('Destekleyici Etkiler', 'Supportive Influences'),
  'fc_sec_influences': (
    'Bu yorumu oluşturan etkiler',
    'Influences behind this reading',
  ),
  'fc_area_general_energy': ('Genel enerji', 'General energy'),
  'fc_area_love': ('Aşk', 'Love'),
  'fc_area_relationships': ('İlişkiler', 'Relationships'),
  'fc_area_career': ('Kariyer', 'Career'),
  'fc_area_money': ('Para', 'Money'),
  'fc_area_mood': ('Duygusal durum', 'Mood'),
  'fc_area_health_balance': ('Sağlık ve denge', 'Health and balance'),
  'fc_area_personal_growth': ('Kişisel gelişim', 'Personal growth'),
  'fc_area_luck': ('Şans', 'Luck'),
  'fc_area_unknown': ('Genel', 'General'),
  'fc_natal': ('natal', 'natal'),
  'fc_angle_asc': ('Yükselen', 'Ascendant'),
  'fc_angle_mc': ('Tepe Noktası (MC)', 'Midheaven (MC)'),
  'fc_angle_dsc': ('Alçalan', 'Descendant'),
  'fc_angle_ic': ('Dip Noktası (IC)', 'Imum Coeli (IC)'),
  'fc_support': ('Destek', 'Support'),
  'fc_caution': ('Dikkat', 'Watch'),
  'fc_supportive': ('Destekleyici', 'Supportive'),
  'fc_challenging': ('Zorlayıcı', 'Challenging'),
  'fc_weight': ('etki %{n}', 'impact {n}%'),
  'fc_badge_opportunity': ('Fırsat', 'Opportunity'),
  'fc_badge_challenge': ('Dikkat', 'Take care'),
  'fc_enters_house': (
    '{planet} {house}. evine geçiyor',
    '{planet} enters your house {house}',
  ),
  'fc_house_meaning': (
    '{theme} temaları {topic} alanına taşınıyor.',
    'Themes of {theme} move into {topic}.',
  ),
  'fc_retrograde': ('{planet} geri hareketi', '{planet} retrograde'),
  'fc_retrograde_meaning': (
    '{theme} konularında gözden geçirme ve yavaşlama dönemi.',
    'A time to review and slow down around {theme}.',
  ),
  'fc_event_new_moon': ('Yeniay', 'New Moon'),
  'fc_event_full_moon': ('Dolunay', 'Full Moon'),
  'fc_event_first_quarter': ('İlk Dördün', 'First Quarter'),
  'fc_event_last_quarter': ('Son Dördün', 'Last Quarter'),
  'fc_event_solar_eclipse': ('Güneş Tutulması', 'Solar Eclipse'),
  'fc_event_lunar_eclipse': ('Ay Tutulması', 'Lunar Eclipse'),
  'fc_event_new_moon_note': (
    'Yeni niyetler ve başlangıçlar için uygun.',
    'Good for new intentions and beginnings.',
  ),
  'fc_event_full_moon_note': (
    'Tamamlama, görünür olma ve duygusal farkındalık.',
    'Completion, visibility and emotional awareness.',
  ),
  'fc_event_first_quarter_note': (
    'Harekete geçme ve karar anı.',
    'A moment to act and decide.',
  ),
  'fc_event_last_quarter_note': (
    'Gözden geçirme ve bırakma zamanı.',
    'Time to review and let go.',
  ),
  'fc_event_solar_eclipse_note': (
    'Güçlü bir başlangıç ve yön değişimi dönemi.',
    'A strong new start and change of direction.',
  ),
  'fc_event_lunar_eclipse_note': (
    'Duygusal tamamlanmalar ve farkındalıklar.',
    'Emotional completions and realisations.',
  ),
  'fc_key_period': ('Öne çıkan dönem: {areas}', 'Key period: {areas}'),
  'fc_month_themes': (
    'Bu ayın ana temaları: {themes}.',
    "This month's main themes: {themes}.",
  ),
  'fc_solar_return': (
    'Güneş dönüşün yeni kişisel yılını başlatıyor.',
    'Your solar return opens a new personal year.',
  ),
  'fc_solar_return_asc': (
    'Bu yılın yükselen tonu: {sign}.',
    "This year's rising tone: {sign}.",
  ),
  'fc_solar_return_sun': ('Odak alanı: {topic}.', 'Focus: {topic}.'),
  'fc_none_dates': (
    'Bu dönemde öne çıkan bir tarih yok.',
    'No standout dates in this period.',
  ),
  'fc_method_note': (
    'Bu öngörü doğum haritan ve gökyüzü hesaplarından üretilir; açıklamalar sabit astrolojik anlamlardır, yapay zekâ hesap yapmaz.',
    'This forecast is calculated from your birth chart and the sky; the explanations are fixed astrological meanings, and no AI does the calculation.',
  ),
  // Phase 1: order lifecycle, booking/cancel confirmation, completion.
  'lifecycle_pending': ('Bekliyor', 'Pending'),
  'lifecycle_paid': ('Ödendi', 'Paid'),
  'lifecycle_scheduled': ('Planlandı', 'Scheduled'),
  'lifecycle_awaiting_completion': (
    'Tamamlanmayı bekliyor',
    'Awaiting completion',
  ),
  'lifecycle_completed': ('Tamamlandı', 'Completed'),
  'lifecycle_cancelled': ('İptal edildi', 'Cancelled'),
  'lifecycle_refund_review': ('İade incelemesinde', 'Refund under review'),
  'lifecycle_refunded': ('İade edildi', 'Refunded'),
  'lifecycle_unknown': ('Durum güncelleniyor', 'Updating status'),
  'payment_status_not_required': ('Ödeme gerekmiyor', 'No payment needed'),
  'payment_status_pending': ('Ödeme bekleniyor', 'Awaiting payment'),
  'payment_status_authorized': ('Ödeme onaylandı', 'Payment authorised'),
  'payment_status_paid': ('Ödendi', 'Paid'),
  'payment_status_failed': ('Ödeme başarısız', 'Payment failed'),
  'payment_status_refund_pending': (
    'İade incelemesinde',
    'Refund under review',
  ),
  'payment_status_refunded': ('İade edildi', 'Refunded'),
  'payment_status_partially_refunded': (
    'Kısmen iade edildi',
    'Partly refunded',
  ),
  'appointment_status_pending': ('Onay bekliyor', 'Awaiting confirmation'),
  'appointment_status_confirmed': ('Onaylandı', 'Confirmed'),
  'appointment_status_completed': ('Tamamlandı', 'Completed'),
  'appointment_status_cancelled': ('İptal edildi', 'Cancelled'),
  'appointment_status_no_show': ('Katılım olmadı', 'No-show'),
  'refund_title': ('İade durumu', 'Refund status'),
  'refund_status_review': ('İade incelemesinde', 'Refund under review'),
  'refund_status_refunded': ('İade edildi', 'Refunded'),
  'refund_status_denied': ('İade reddedildi', 'Refund declined'),
  'refund_status_failed': (
    'İade işlemi tamamlanamadı; destek ekibi inceliyor.',
    'The refund could not be completed; support is looking into it.',
  ),
  'booking_confirm_title': ('Randevuyu onayla', 'Confirm your booking'),
  'booking_date': ('Tarih', 'Date'),
  'booking_time': ('Saat', 'Time'),
  'booking_timezone': ('Saat dilimi', 'Time zone'),
  'booking_expert': ('Uzman', 'Expert'),
  'booking_service': ('Hizmet', 'Service'),
  'booking_confirm': ('Onayla ve devam et', 'Confirm and continue'),
  'booking_pick_time': (
    'Bu gün için bir saat seç.',
    'Pick a time on this day.',
  ),
  'slot_date_mismatch': (
    'Seçtiğin saat seçili güne ait değil. Lütfen saati yeniden seç.',
    'The chosen time is not on the selected day. Please pick the time again.',
  ),
  'cancel_confirm_title': (
    'İptal etmek istediğine emin misin?',
    'Cancel this booking?',
  ),
  'cancel_refund_review': (
    'Ödemen ({amount}) iade incelemesine alınır. İadeyi bir yetkili inceler; tutar ve süre inceleme sonunda netleşir.',
    'Your payment ({amount}) goes to a refund review. A person reviews it; the amount and timing are confirmed after the review.',
  ),
  'cancel_not_paid': (
    'Ödeme alınmadı; iade gerekmez.',
    'No payment was taken; nothing to refund.',
  ),
  'cancel_free': (
    'Ücretsiz hizmet; iade gerekmez.',
    'Free service; nothing to refund.',
  ),
  'cancel_booking': ('Randevuyu iptal et', 'Cancel booking'),
  'cancel_keep': ('Vazgeç', 'Keep it'),
  'cancel_confirm': ('İptal et', 'Cancel booking'),
  'cancel_done': ('İptal edildi.', 'Cancelled.'),
  'order_payment': ('Ödeme', 'Payment'),
  'order_total': ('Tutar', 'Total'),
  'payment_confirmed': ('Ödeme onaylandı', 'Payment confirmed'),
  'go_to_call': ('Görüşmeye Git', 'Go to session'),
  'view_appointment': ('Randevuyu Gör', 'View appointment'),
  'open_order': ('Siparişi gör', 'View order'),
  'call_ended_next_step': (
    'Görüşme gerçekleştiyse siparişten tamamlandı olarak işaretleyebilirsin.',
    'If the session took place, you can mark it completed from the order.',
  ),
  'complete_action': (
    'Hizmet gerçekleşti olarak işaretle',
    'Mark the session as completed',
  ),
  'complete_confirm': (
    'Hizmetin gerçekleştiğini onaylıyor musun? Onaydan sonra değerlendirme yapabilirsin.',
    'Confirm the session took place? You can leave a review afterwards.',
  ),
  'complete_waiting': (
    'Seans başladıktan sonra tamamlanabilir.',
    'Can be completed once the session has started.',
  ),
  'deliver_title': ('Yazılı analizi teslim et', 'Deliver the written analysis'),
  'deliver_hint': ('Analiz metni', 'Analysis text'),
  'deliver_action': ('Teslim et', 'Deliver'),
  'delivery_title': ('Teslim edilen analiz', 'Delivered analysis'),
  'filter_upcoming': ('Yaklaşan', 'Upcoming'),
  'filter_past': ('Geçmiş', 'Past'),
  'filter_cancelled': ('İptal edilen', 'Cancelled'),
  'timeline': ('Zaman çizelgesi', 'Timeline'),
  'timeline_created': ('Sipariş oluşturuldu', 'Order placed'),
  'timeline_paid': ('Ödeme alındı', 'Payment received'),
  'timeline_session_scheduled': ('Seans zamanı', 'Session time'),
  'timeline_delivered': ('Analiz teslim edildi', 'Analysis delivered'),
  'timeline_completed': ('Tamamlandı', 'Completed'),
  'timeline_cancelled': ('İptal edildi', 'Cancelled'),
  'timeline_refund_requested': (
    'İade incelemesi açıldı',
    'Refund review opened',
  ),
  'timeline_refunded': ('İade edildi', 'Refunded'),
  'timeline_refund_denied': ('İade reddedildi', 'Refund declined'),
  // Phase 2: account centre, notification centre, profile menu.
  'account_center': ('Hesap Merkezi', 'Account Centre'),
  'account_info': ('Hesap Bilgileri', 'Account information'),
  'account_info_sub': (
    'Ad, dil ve yaşadığın yer',
    'Name, language and where you live',
  ),
  'birth_data_title': ('Doğum Bilgileri', 'Birth details'),
  'birth_data_sub': (
    'Doğum haritanın dayandığı bilgiler',
    'What your birth chart is built on',
  ),
  'birth_data_intro': (
    'Doğum tarihin, saatin ve yerin doğum haritanı belirler. Yaşadığın yer burada değil, Hesap Bilgileri\'nde değişir.',
    'Your birth date, time and place define your chart. Where you live now is changed in Account information, not here.',
  ),
  'email': ('E-posta', 'Email'),
  'current_timezone': (
    'Yaşadığın yer (saat dilimi)',
    'Where you live (time zone)',
  ),
  'current_timezone_note': (
    'Günlük içerik, randevu saatleri ve bildirimler buna göre gösterilir. Doğum haritan değişmez.',
    'Daily content, appointment times and notifications follow this. Your birth chart does not change.',
  ),
  'current_city_search': ('Şehir ara', 'Search a city'),
  'privacy_security': ('Gizlilik ve Güvenlik', 'Privacy and security'),
  'change_password': ('Şifre Değiştir', 'Change password'),
  'password_change_note': (
    'Şifreni değiştirdiğinde diğer cihazlardaki oturumların kapanır; bu cihazda oturumun açık kalır.',
    'Changing your password signs out your other devices; this one stays signed in.',
  ),
  'password_current': ('Mevcut şifre', 'Current password'),
  'password_new': ('Yeni şifre', 'New password'),
  'password_repeat': ('Yeni şifre (tekrar)', 'New password (again)'),
  'password_min': (
    'Şifre en az 8 karakter olmalı.',
    'Use at least 8 characters.',
  ),
  'password_spaces': (
    'Şifre boşlukla başlayamaz veya bitemez.',
    'The password cannot start or end with a space.',
  ),
  'password_same': (
    'Yeni şifre mevcut şifreden farklı olmalı.',
    'The new password must differ from the current one.',
  ),
  'password_mismatch': ('Şifreler eşleşmiyor.', 'The passwords do not match.'),
  'password_changed': ('Şifren değiştirildi.', 'Your password was changed.'),
  'password_wrong_current': (
    'Mevcut şifre hatalı.',
    'The current password is incorrect.',
  ),
  'password_weak': (
    'Bu şifre kabul edilmedi; daha güçlü bir şifre seç.',
    'That password was not accepted; choose a stronger one.',
  ),
  'password_change_unsupported': (
    'Bu hesap için şifre burada değiştirilemiyor.',
    'The password for this account cannot be changed here.',
  ),
  'sessions_title': ('Oturumlar ve Cihazlar', 'Sessions and devices'),
  'sessions_signed_in': ('Açık oturumlar', 'Signed-in sessions'),
  'sessions_none': (
    'E-posta ve şifreyle açılmış başka oturum yok.',
    'No email-and-password sessions.',
  ),
  'sessions_this_device': ('Bu cihaz', 'This device'),
  'sessions_last_used': ('Son kullanım', 'Last used'),
  'sessions_sign_out': ('Oturumu kapat', 'Sign out'),
  'devices_title': (
    'Bildirim alan cihazlar',
    'Devices receiving notifications',
  ),
  'devices_none': ('Kayıtlı cihaz yok.', 'No registered devices.'),
  'devices_remove': ('Kaldır', 'Remove'),
  'delete_account': ('Hesabı Sil', 'Delete account'),
  'delete_account_intro': (
    'Hesabın devre dışı bırakılır; tüm oturumların kapanır ve bu hesapla giriş yapamazsın. Sipariş ve ödeme kayıtları saklanır. Mesajlar, görseller ve profil verileri bu işlemde anında silinmez. Bunlar için ayrıca destek ekibine silme talebi gönderebilirsin.',
    'Your account is deactivated and all sessions are closed. Order and payment records are retained. Messages, images, and profile data are not immediately erased by this action. You can separately request their deletion from support.',
  ),
  'delete_type_email': (
    'Onay için e-posta adresini yaz',
    'Type your email address to confirm',
  ),
  'delete_understood': (
    'Hesabımın devre dışı bırakılacağını ve bu hesapla giriş yapamayacağımı anlıyorum.',
    'I understand my account will be deactivated and I will no longer be able to sign in with it.',
  ),
  'delete_account_final': (
    'Hesabını silmek üzeresin. Emin misin?',
    'You are about to delete your account. Are you sure?',
  ),
  'delete_email_mismatch': (
    'E-posta adresi hesabınla eşleşmiyor.',
    'The email address does not match your account.',
  ),
  'delete_blocked': (
    'Açık randevu, sipariş veya iade varken hesap silinemez. Önce bunları tamamla ya da iptal et.',
    'The account cannot be deleted while an appointment, order or refund is open. Finish or cancel them first.',
  ),
  'delete_blocked_appointments': (
    '{n} aktif randevu',
    '{n} active appointment(s)',
  ),
  'delete_blocked_orders': (
    '{n} tamamlanmamış sipariş',
    '{n} unfinished order(s)',
  ),
  'delete_blocked_refunds': (
    '{n} incelemedeki iade',
    '{n} refund(s) under review',
  ),
  'delete_blocked_expert': (
    'Uzman olarak {n} açık sipariş',
    '{n} open order(s) as an expert',
  ),
  'menu_account': ('Hesabım', 'My account'),
  'menu_profile': ('Profil', 'Profile'),
  'menu_services': ('Hizmetlerim', 'My services'),
  'menu_messages': ('Mesajlarım', 'My messages'),
  'menu_reports': ('Raporlarım', 'My reports'),
  'call_history': ('Görüşme Geçmişi', 'Call history'),
  'menu_plan': ('Planım', 'My plan'),
  'menu_settings': ('Ayarlar', 'Settings'),
  'menu_expert': ('Uzman', 'Expert'),
  'notifications_title': ('Bildirimler', 'Notifications'),
  'inbox_intro': (
    'Randevu, mesaj, ödeme ve rapor bildirimlerin.',
    'Your appointment, message, payment and report notifications.',
  ),
  'notifications_read_all': ('Tümünü okundu yap', 'Mark all read'),
  'notifications_empty': ('Henüz bildirimin yok.', 'No notifications yet.'),
  'notifications_mark_read': ('Okundu işaretle', 'Mark as read'),
  'notifications_mark_unread': ('Okunmadı işaretle', 'Mark as unread'),
  'notif_cat_astro_ai': ('Astro AI / Rapor', 'Astro AI / Report'),
  'notif_cat_appointment': ('Randevu', 'Appointment'),
  'notif_cat_expert_message': ('Danışman mesajı', 'Expert message'),
  'notif_cat_payment': ('Ödeme / İade', 'Payment / Refund'),
  'notif_cat_system': ('Sistem', 'System'),
  'notif_cat_promotion': ('Promosyon', 'Promotion'),
  'notif_title_generic': ('Bildirim', 'Notification'),
  'notif_title_appointment_booked': (
    'Randevun oluşturuldu',
    'Your appointment is booked',
  ),
  'notif_title_appointment_cancelled': (
    'Bir randevun iptal edildi',
    'An appointment was cancelled',
  ),
  'notif_title_appointment_reminder': (
    'Yaklaşan randevun var',
    'Upcoming appointment',
  ),
  'notif_hours_before': ('{n} saat kaldı', 'in {n} h'),
  'session_this_app': ('Astrofrekans uygulaması', 'Astrofrekans app'),
  'notif_minutes_before': ('{n} dk kaldı', 'in {n} min'),
  'notif_title_order_status_changed': (
    'Siparişinde güncelleme var',
    'Your order was updated',
  ),
  'notif_title_call_missed': ('Cevapsız görüşme', 'Missed call'),
  'notif_title_new_chat_message': (
    'Danışmanından yeni mesaj',
    'New message from your expert',
  ),
  'notif_title_payment_succeeded': ('Ödemen alındı', 'Payment received'),
  'notif_title_payment_failed': (
    'Ödemen tamamlanamadı',
    'Payment did not go through',
  ),
  'notif_title_refund_processed': (
    'İaden işlendi',
    'Your refund was processed',
  ),
  'notif_title_subscription_renewed': (
    'Aboneliğin yenilendi',
    'Your subscription renewed',
  ),
  'notif_title_subscription_expired': (
    'Aboneliğinin süresi doldu',
    'Your subscription expired',
  ),
  'notif_title_ai_report_ready': (
    'Astro AI yorumun hazır',
    'Your Astro AI reading is ready',
  ),
  'notif_title_daily_content': (
    'Bugünün gökyüzü hazır',
    'Today\'s sky is ready',
  ),
  'notif_title_promotion': ('Sana özel yeni içerik', 'Something new for you'),
  'plans_load_failed': ('Planlar yüklenemedi.', 'Plans could not be loaded.'),
  'plans_empty': (
    'Şu anda gösterilecek plan yok.',
    'No plans to show right now.',
  ),
  'search_experts': (
    'İsim, uzmanlık veya konu ara',
    'Search name, specialty or topic',
  ),
  'edit': ('Düzenle', 'Edit'),
  'person_edit_note': (
    'Değişiklik yeni raporlarda kullanılır; daha önce oluşturulan raporlar değişmez.',
    'Changes apply to new reports; reports already made stay as they were.',
  ),
  // Phase 2 audit: live session and order payment copy.
  'call_err_call_too_early': (
    'Görüşme zamanı henüz gelmedi.',
    'It is not time for this session yet.',
  ),
  'call_err_call_window_closed': (
    'Görüşmeye katılım süresi sona erdi.',
    'The time to join this session has passed.',
  ),
  'call_err_call_not_allowed': (
    'Bu görüşme için yetkin bulunmuyor.',
    'You are not allowed to join this session.',
  ),
  'call_err_call_provider_not_configured': (
    'Canlı görüşme bu ortamda yapılandırılmamış.',
    'Live sessions are not configured here.',
  ),
  'call_err_call_already_ended': (
    'Bu görüşme sona erdi.',
    'This session has ended.',
  ),
  'call_err_call_type_not_supported': (
    'Bu görüşme türü desteklenmiyor.',
    'This session type is not supported.',
  ),
  'call_err_call_provider_unavailable': (
    'Görüşme servisine şu anda ulaşılamıyor.',
    'The call service cannot be reached right now.',
  ),
  'call_err_duplicate_identity': (
    'Bu görüşme başka bir cihazda açıldı.',
    'This session was opened on another device.',
  ),
  'call_err_generic': (
    'Görüşme şu anda kullanılamıyor. Lütfen yeniden dene.',
    'The session is unavailable right now. Please try again.',
  ),
  'call_history_empty': ('Henüz görüşme yok.', 'No calls yet.'),
  'call_video': ('Görüntülü görüşme', 'Video session'),
  'call_audio': ('Sesli görüşme', 'Voice session'),
  'call_duration_pending': ('Süre henüz belirlenmedi', 'Duration not set yet'),
  'call_live': ('Canlı Görüşme', 'Live session'),
  'call_incoming': ('Gelen Görüşme', 'Incoming call'),
  'call_server_checks': (
    'Görüşmeye katılma iznini ve saat aralığını sunucu denetler.',
    'The server checks who may join and when.',
  ),
  'call_reconnecting': (
    'Bağlantı yeniden kuruluyor. Görüşme sunucuda sürüyor.',
    'Reconnecting. The session continues on the server.',
  ),
  'call_permission_settings': (
    'Kamera veya mikrofon izni ayarlardan açılmalı.',
    'Turn on camera or microphone access in Settings.',
  ),
  'call_permission_denied': (
    'Görüşme için gerekli izin verilmedi.',
    'The permission the session needs was not given.',
  ),
  'call_open_settings': ('Ayarları aç', 'Open Settings'),
  'call_accept': ('Görüşmeyi kabul et', 'Accept'),
  'call_join': ('Görüşmeye katıl', 'Join'),
  'call_end': ('Görüşmeyi bitir', 'End session'),
  'call_ended': ('Görüşme sona erdi.', 'The session has ended.'),
  'call_video_title': (
    'Görüntülü Uzman Görüşmesi',
    'Video session with an expert',
  ),
  'call_audio_title': ('Sesli Uzman Görüşmesi', 'Voice session with an expert'),
  'call_state': ('Görüşme', 'Session'),
  'call_connection': ('Bağlantı', 'Connection'),
  'call_status_scheduled': ('Planlandı', 'Scheduled'),
  'call_status_waiting': ('Bekleniyor', 'Waiting'),
  'call_status_ringing': ('Çalıyor', 'Ringing'),
  'call_status_active': ('Sürüyor', 'In progress'),
  'call_status_ended': ('Sona erdi', 'Ended'),
  'call_status_missed': ('Cevapsız', 'Missed'),
  'call_status_cancelled': ('İptal edildi', 'Cancelled'),
  'call_status_failed': ('Başarısız', 'Failed'),
  'call_status_unknown': ('Bilinmiyor', 'Unknown'),
  'call_conn_connecting': ('bağlanıyor', 'connecting'),
  'call_conn_connected': ('bağlı', 'connected'),
  'call_conn_reconnecting': ('yeniden bağlanıyor', 'reconnecting'),
  'call_conn_disconnected': ('bağlı değil', 'disconnected'),
  'call_conn_failed': ('başarısız', 'failed'),
  'call_conn_replaced': ('başka cihazda', 'on another device'),
  'call_mic_on': ('Mikrofonu aç', 'Unmute'),
  'call_mic_off': ('Mikrofonu kapat', 'Mute'),
  'call_to_earpiece': ('Kulaklığa geç', 'Use earpiece'),
  'call_to_speaker': ('Hoparlöre geç', 'Use speaker'),
  'call_camera_off': ('Kamerayı kapat', 'Camera off'),
  'call_camera_on': ('Kamerayı aç', 'Camera on'),
  'call_camera_switch': ('Kamerayı değiştir', 'Switch camera'),
  'call_audio_output': ('Ses çıkışı seç', 'Choose audio output'),
  'pay_redirected': (
    'Ödeme sağlayıcısına yönlendirildin. Durumu yenileyerek kontrol et.',
    'You were sent to the payment provider. Refresh to check the status.',
  ),
  'pay_credit_checked': (
    'Kredi işlemi sunucuda kontrol edildi.',
    'The credit was checked on the server.',
  ),
  'pay_external_failed': (
    'Harici ödeme şu anda başlatılamıyor. Sipariş durumu değişmedi.',
    'The external payment cannot start right now. The order is unchanged.',
  ),
  'pay_credit_failed': (
    'Kredi sunucuda uygulanamadı. Sipariş durumu değişmedi.',
    'The credit could not be applied. The order is unchanged.',
  ),
  'pay_groups': ('Ödeme grupları', 'Payment groups'),
  'pay_review_blocked': (
    'Bu hizmetin ödeme yöntemi inceleme bekliyor; ödeme başlatılamaz.',
    'This service\'s payment method is under review; payment cannot start.',
  ),
  'pay_expert_start': ('Uzman ödemesine geç', 'Pay for the expert session'),
  'pay_refresh': ('Ödeme durumunu yenile', 'Refresh payment status'),
  'pay_digital_unavailable': (
    'Dijital ürün mağazada şu anda kullanılamıyor.',
    'The digital product is not available in the store right now.',
  ),
  'pay_apply_credit': ('Doğrulanmış krediyi uygula', 'Apply verified credit'),
  'pay_group_digital': (
    'Dijital ürün · uygulama mağazası',
    'Digital product · app store',
  ),
  'pay_group_live': (
    'Canlı uzman hizmeti · harici sağlayıcı',
    'Live expert service · external provider',
  ),
  'pay_group_review': (
    'Ödeme yöntemi inceleme bekliyor',
    'Payment method under review',
  ),
  'pay_group_free': ('Ücretsiz', 'Free'),
  'pay_group_unknown': ('Ödeme yöntemi belirlenmedi', 'Payment method not set'),
  'pay_status_required': ('Ödeme gerekli', 'Payment required'),
  'pay_status_satisfied': ('Sunucuda ödendi', 'Paid (verified)'),
  'pay_status_blocked': ('İnceleme nedeniyle kapalı', 'Closed pending review'),
  'pay_status_not_required': ('Ödeme gerekmiyor', 'No payment needed'),
  'pay_status_refunded': ('İade edildi', 'Refunded'),
  'pay_status_unknown': ('Durum doğrulanamadı', 'Status could not be verified'),
  'report_err_coins': (
    'AstroCoin bakiyen yetmiyor; hiçbir coin düşülmedi.',
    'Not enough AstroCoins; nothing was deducted.',
  ),
  'report_err_payment': (
    'Rapor için doğrulanmış kredi gerekli. Önce kredi satın al.',
    'The report needs a verified credit. Buy a credit first.',
  ),
  'report_err_conflict': (
    'Rapor isteği çakıştı. Yeniden dene; yeni bir istek kimliği kullanılacak.',
    'The report request clashed. Try again; a new request id will be used.',
  ),
  'report_err_unavailable': (
    'Ayrılan rapor kredisi artık kullanılamıyor. Bakiyeni yenile.',
    'The reserved report credit is no longer available. Refresh your balance.',
  ),
  'report_err_generic': (
    'Rapor tamamlanamadı. Tekrar dene; aynı istek kimliği korunur.',
    'The report could not be completed. Try again; the same request id is kept.',
  ),
  'report_credits_title': (
    'Doğrulanmış rapor kredileri',
    'Verified report credits',
  ),
  'report_natal': ('Doğum haritası raporu', 'Birth chart report'),
  'report_synastry': ('Sinastri raporu', 'Synastry report'),
  'report_annual': ('Yıllık öngörü raporu', 'Annual forecast report'),
  'report_buy_credit': ('Kredi satın al', 'Buy credit'),
  'report_synastry_pending': (
    'Sinastri için kaynak harita seçimi henüz bağlı değil; kredi korunur.',
    'Choosing the charts for synastry is not connected yet; your credit is kept.',
  ),
  'report_create_with_credit': (
    'Doğrulanmış krediyle rapor oluştur',
    'Create the report with a verified credit',
  ),
  // Transit meanings (fixed astrological themes; was transit_meaning.dart).
  'transit_theme_sun': ('kimlik ve yaşam enerjisi', 'identity and vitality'),
  'transit_theme_moon': ('duygular ve ihtiyaçlar', 'emotions and needs'),
  'transit_theme_mercury': (
    'düşünce ve iletişim',
    'thinking and communication',
  ),
  'transit_theme_venus': ('sevgi, değer ve keyif', 'love, value and pleasure'),
  'transit_theme_mars': (
    'enerji, istek ve mücadele',
    'drive, desire and effort',
  ),
  'transit_theme_jupiter': (
    'büyüme, fırsat ve anlam',
    'growth, opportunity and meaning',
  ),
  'transit_theme_saturn': (
    'sorumluluk, sınır ve yapı',
    'responsibility, limits and structure',
  ),
  'transit_theme_uranus': ('değişim ve özgürlük', 'change and freedom'),
  'transit_theme_neptune': (
    'sezgi, hayal ve teslimiyet',
    'intuition, imagination and surrender',
  ),
  'transit_theme_pluto': (
    'güç, derinlik ve dönüşüm',
    'power, depth and transformation',
  ),
  'transit_theme_northNode': ('gelişim yönü', 'direction of growth'),
  'transit_theme_southNode': ('alışkanlıklar ve geçmiş', 'habits and the past'),
  'transit_house_1': ('kendin ve bedenin', 'yourself and your body'),
  'transit_house_2': ('para ve öz değer', 'money and self-worth'),
  'transit_house_3': (
    'iletişim ve yakın çevre',
    'communication and close circle',
  ),
  'transit_house_4': ('ev ve aile', 'home and family'),
  'transit_house_5': ('aşk ve yaratıcılık', 'romance and creativity'),
  'transit_house_6': ('günlük düzen ve iş akışı', 'daily routine and workflow'),
  'transit_house_7': (
    'ilişkiler ve ortaklıklar',
    'relationships and partnerships',
  ),
  'transit_house_8': (
    'ortak kaynaklar ve dönüşüm',
    'shared resources and transformation',
  ),
  'transit_house_9': ('inançlar ve öğrenme', 'beliefs and learning'),
  'transit_house_10': ('kariyer ve hedefler', 'career and goals'),
  'transit_house_11': (
    'arkadaşlar ve gelecek planları',
    'friends and future plans',
  ),
  'transit_house_12': ('dinlenme ve iç gözlem', 'rest and reflection'),
  'transit_angle_asc': (
    'kişisel ifade ve görünürlük',
    'self-expression and visibility',
  ),
  'transit_angle_mc': (
    'kariyer ve toplumsal hedefler',
    'career and public goals',
  ),
  'transit_angle_dsc': (
    'ilişkiler ve ortaklıklar',
    'relationships and partnerships',
  ),
  'transit_angle_ic': ('ev ve iç dünya', 'home and inner life'),
  'transit_in_house': (
    '{moving} temaları {house}. evinde: {topic} gündemde.',
    'Themes of {moving} move through your house {house}: {topic} are in focus.',
  ),
  'transit_prominent': (
    '{moving} temaları gökyüzünde belirgin.',
    'Themes of {moving} are prominent in the sky.',
  ),
  'transit_aspect_harmonious': (
    '{moving} temaları, {natal} alanını destekliyor; akıştan yararlanmak için uygun bir dönem.',
    'Themes of {moving} support your {natal}; a good window to use the flow.',
  ),
  'transit_aspect_hard': (
    '{moving} temaları, {natal} alanında baskı ve sınav yaratabilir; zorlamak yerine yapı kurmak işe yarar.',
    'Themes of {moving} may press on your {natal}; building structure works better than forcing.',
  ),
  'transit_aspect_neutral': (
    '{moving} temaları, {natal} alanıyla birleşiyor; bu konu belirgin biçimde öne çıkıyor.',
    'Themes of {moving} merge with your {natal}; this area comes strongly to the fore.',
  ),
  'ok': ('Tamam', 'OK'),
  'password_external_note': (
    '{provider} ile giriş yapıyorsun; şifren {provider} hesabında yönetilir. Burada değiştirilecek bir şifre yok.',
    'You sign in with {provider}; your password is managed in your {provider} account. There is no password to change here.',
  ),
  'password_external_provider': ('giriş sağlayıcın', 'your sign-in provider'),
  'password_recent_login': (
    'Güvenlik için yeniden giriş yapman gerekiyor. Çıkış yapıp tekrar giriş yap, sonra yeniden dene.',
    'For security, sign in again first. Sign out, sign back in, then try again.',
  ),
  'sessions_firebase': ('Firebase ile giriş', 'Firebase sign-in'),
  'sessions_firebase_managed': (
    'Firebase tarafından yönetiliyor',
    'Managed by Firebase',
  ),
  'sessions_signed_in_at': ('Giriş', 'Signed in'),
  'sessions_provider_password': ('e-posta ve şifre', 'email and password'),
  'sessions_firebase_note': (
    'Bu oturum Firebase tarafından yönetiliyor; buradan kapatılamaz. Diğer cihazlardaki Firebase oturumları bu listede görünmez. Bir cihazdan çıkmak için o cihazda Çıkış Yap\'ı kullan.',
    'This sign-in is managed by Firebase and cannot be closed from here. Firebase sign-ins on other devices do not appear in this list. To leave a device, use Sign out on that device.',
  ),
  'purchase_in_progress': ('Satın alma sürüyor…', 'Purchase in progress…'),
  'purchase_verifying': (
    'Satın alma doğrulanıyor…',
    'Verifying your purchase…',
  ),
  'purchase_succeeded': (
    'Satın alma tamamlandı; erişimin açıldı.',
    'Purchase complete; your access is on.',
  ),
  'restore_in_progress': (
    'Satın alımlar geri yükleniyor…',
    'Restoring purchases…',
  ),
  'restore_done': (
    'Satın alımların geri yüklendi.',
    'Your purchases were restored.',
  ),
  'restore_nothing': (
    'Bu hesaba ait geri yüklenecek bir satın alma bulunamadı.',
    'No purchases to restore were found for this account.',
  ),
  'billing_error_product_unavailable': (
    'Ürün mağazada bulunamadı.',
    'This product is not available in the store.',
  ),
  'billing_error_store_unavailable': (
    'Mağaza şu anda kullanılamıyor.',
    'The store is not available right now.',
  ),
  'billing_error_store_no_answer': (
    'Mağazadan yanıt gelmedi. Ödeme alındıysa kısa süre içinde işlenir; gerekirse satın alımları geri yükle.',
    'The store did not answer. If you were charged it will be processed shortly; you can also restore purchases.',
  ),
  'billing_error_verification_failed': (
    'Satın alma sunucuda doğrulanamadı. Erişim açılmadı.',
    'The purchase could not be verified. Access was not granted.',
  ),
  'billing_error_restore_failed': (
    'Geri yükleme tamamlanamadı. Tekrar deneyin.',
    'Restore could not be completed. Please try again.',
  ),
  'billing_error_entitlement_refresh_failed': (
    'Erişim durumu alınamadı. Tekrar deneyin.',
    'Your access status could not be loaded. Please try again.',
  ),
  'billing_error_already_owned': (
    'Bu ürün zaten hesabında. Erişimini geri getirmek için satın alımları geri yükle.',
    'You already own this. Restore purchases to get your access back.',
  ),
  'billing_error_generic': (
    'Ödeme işlemi tamamlanamadı.',
    'The payment could not be completed.',
  ),
  'reports_special_title': ('Özel raporlar', 'Special reports'),
  'reset_requested_firebase_only': (
    'Hesap varsa sıfırlama bağlantısı e-postana gönderildi. Uzman ve sunucu hesapları için sıfırlama e-postası şu an gönderilemiyor; bu hesaplar için destekle iletişime geç.',
    'If the account exists, a reset link was sent to your email. Reset emails cannot be sent for expert and server accounts right now; for those, please contact support.',
  ),
  'complete_birth_data': (
    'Doğum bilgilerini tamamla',
    'Complete birth details',
  ),
  'birth_data_needed_hint': (
    'Doğum saatini bilmiyorsan Güneş burcu ve gezegen konumları yine hesaplanır; ancak yükselen burç, evler ve dönüş haritaları doğum saati olmadan hesaplanamaz.',
    'Without a birth time your Sun sign and planet positions can still be calculated, but the rising sign, houses and return charts cannot.',
  ),
  'ai_writing': ('Astro AI yazıyor', 'Astro AI is writing'),
  'ai_reading_chart': (
    'Astro AI haritanı okuyor',
    'Astro AI is reading your chart',
  ),
  'ai_reading_cards': (
    'Astro AI kartlarını yorumluyor',
    'Astro AI is interpreting your cards',
  ),
};
